################################################################################
# /packages/plant_euphorbia_leuconeura.yaml
################################################################################
#
# Мониторинг Молочая (Euphorbia leuconeura):
#   • почва (нужно ли полить)
#   • температура (слишком холодно / жарко)
#   • освещённость (слишком ярко / слишком темно) — если поддерживается
#
# Фишки:
#   - Гистерезис по влажности почвы (не спамить после полива)
#   - Не оповещаем во время старта системы
#   - Триггеры требуют устойчивого плохого состояния (for:)
#   - Кулдаун между одинаковыми напоминаниями
################################################################################

##############################################################################
#                             ВХОДНЫЕ ПЕРЕМЕННЫЕ
##############################################################################
input_text:
  notification_history_euphorbia_leuconeura:
    name: "Молочай: История уведомлений"

input_datetime:
  last_euphorbia_leuconeura_soil_notification:
    name: "Last Euphorbia Soil Notification Time"
    has_date: true
    has_time: true
    initial: "1970-01-01 00:00:00"

  last_euphorbia_leuconeura_temperature_notification:
    name: "Last Euphorbia Temperature Notification Time"
    has_date: true
    has_time: true
    initial: "1970-01-01 00:00:00"

  last_euphorbia_leuconeura_illuminance_notification:
    name: "Last Euphorbia Illuminance Notification Time"
    has_date: true
    has_time: true
    initial: "1970-01-01 00:00:00"

##############################################################################
#                                 СЕНСОРЫ
##############################################################################
sensor:
  # Температура (сглаженная)
  - platform: filter
    name: "euphorbia_leuconeura_filtered_temperature"
    entity_id: sensor.euphorbia_leuconeura_temperature
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2

  # Влажность воздуха рядом с растением (сглаженная)
  - platform: filter
    name: "euphorbia_leuconeura_filtered_air_humidity"
    entity_id: sensor.euphorbia_leuconeura_air_humidity
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2

  # Влажность почвы (сглаженная)
  - platform: filter
    name: "euphorbia_leuconeura_filtered_soil_moisture"
    entity_id: sensor.euphorbia_leuconeura_soil_moisture
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2

  # Освещённость (сглаженная)
  - platform: filter
    name: "euphorbia_leuconeura_filtered_illuminance"
    entity_id: sensor.euphorbia_leuconeura_illuminance
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2

##############################################################################
#                            БИНАРНЫЕ СЕНСОРЫ
##############################################################################
binary_sensor:
  - platform: template
    sensors:
      # ----------------------------------------------------------------------
      # НУЖЕН ПОЛИВ (гистерезис + не пищим если перелито)
      # ----------------------------------------------------------------------
      plant_alert_euphorbia_leuconeura_soil:
        unique_id: plant_alert_euphorbia_leuconeura_soil
        friendly_name: "Необходимость полива (Молочай)"
        device_class: problem
        availability_template: >-
          {{ states('sensor.euphorbia_leuconeura_filtered_soil_moisture') not in ['unknown','unavailable','none',''] and
             states('number.euphorbia_leuconeura_min_soil_moisture') not in ['unknown','unavailable','none',''] and
             states('number.euphorbia_leuconeura_max_soil_moisture') not in ['unknown','unavailable','none',''] }}
        value_template: >-
          {% set moisture = states('sensor.euphorbia_leuconeura_filtered_soil_moisture') | float(0) %}
          {% set min_thr  = states('number.euphorbia_leuconeura_min_soil_moisture') | float(0) %}
          {% set max_thr  = states('number.euphorbia_leuconeura_max_soil_moisture') | float(9999) %}
          {% set was_on   = is_state('binary_sensor.plant_alert_euphorbia_leuconeura_soil','on') %}

          {# Логика такая же, как у фикуса:
             1. Если почва слишком мокрая (> max_thr) → не просим полива.
             2. Если уже просили полить (was_on),
                держим "просим полить" пока не уйдём заметно выше минимума.
                Берём гистерезис +5%.
             3. Если до этого не просили, включаем только если реально ниже минимума.
          #}

          {% set release_thr = min_thr + 5 %}
          {% if moisture > max_thr %}
            false
          {% elif was_on %}
            {{ moisture < release_thr }}
          {% else %}
            {{ moisture < min_thr }}
          {% endif %}

      # ----------------------------------------------------------------------
      # ТЕМПЕРАТУРА ВНЕ ДИАПАЗОНА
      # ----------------------------------------------------------------------
      plant_alert_euphorbia_leuconeura_temperature:
        unique_id: plant_alert_euphorbia_leuconeura_temperature
        friendly_name: "Необходимость согрева или охлаждения (Молочай)"
        device_class: problem
        availability_template: >-
          {{ states('sensor.euphorbia_leuconeura_filtered_temperature') not in ['unknown','unavailable','none',''] and
             states('number.euphorbia_leuconeura_min_temperature') not in ['unknown','unavailable','none',''] and
             states('number.euphorbia_leuconeura_max_temperature') not in ['unknown','unavailable','none',''] }}
        value_template: >-
          {% set t    = states('sensor.euphorbia_leuconeura_filtered_temperature') | float(0) %}
          {% set tmin = states('number.euphorbia_leuconeura_min_temperature') | float(0) %}
          {% set tmax = states('number.euphorbia_leuconeura_max_temperature') | float(0) %}
          {{ (t > 0 and t < tmin) or (t > tmax) }}

      # ----------------------------------------------------------------------
      # ОСВЕЩЁННОСТЬ (слишком ярко / слишком темно)
      # ----------------------------------------------------------------------
      plant_alert_euphorbia_leuconeura_illuminance:
        unique_id: plant_alert_euphorbia_leuconeura_illuminance
        friendly_name: "Необходимость коррекции освещенности (Молочай)"
        device_class: problem
        availability_template: >-
          {{ states('sensor.euphorbia_leuconeura_filtered_illuminance') not in ['unknown','unavailable','none',''] and
             states('number.euphorbia_leuconeura_max_illuminance') not in ['unknown','unavailable','none',''] }}
        value_template: >-
          {% set lux     = states('sensor.euphorbia_leuconeura_filtered_illuminance') | float(0) %}
          {% set max_lux = states('number.euphorbia_leuconeura_max_illuminance') | float(0) %}
          {{ lux > 0 and lux > max_lux }}
          {# если захочешь ловить "мало света", можно добавить min_lux
             и проверять (lux < min_lux) или (lux > max_lux)
          #}

##############################################################################
#                              АВТОМАТИЗАЦИИ
##############################################################################
automation:
  # --------------------------------------------------------------------------
  # Полив: отправить уведомление, если молочай реально пересох
  # --------------------------------------------------------------------------
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-1"
    alias: "Растение. Молочай: Уведомление о поливе"
    description: >
      Если 'почва сухая' держится включённой 30 минут,
      ты дома, система не в старте, и кулдаун прошёл — напомним полить.
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_soil
        to: "on"
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.last_euphorbia_leuconeura_soil_notification') %}
          {% set last_ts = as_timestamp(last) if last not in ['unknown','unavailable','none'] else 0 %}
          {% set cooldown = (states('input_number.plants_notification_cooldown_hours') | float(3) * 3600) | int %}
          {{ (now().timestamp() - last_ts) > cooldown }}
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Молочай"
          plant_name_latin: "euphorbia_leuconeura"

  # --------------------------------------------------------------------------
  # Температура: уведомление о "слишком холодно / слишком жарко"
  # --------------------------------------------------------------------------
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-2"
    alias: "Растение. Молочай: Уведомление о температуре"
    description: >
      Если температура вне диапазона 10 минут,
      ты дома, не старт системы, кулдаун прошёл — уведомляем.
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_temperature
        to: "on"
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.last_euphorbia_leuconeura_temperature_notification') %}
          {% set last_ts = as_timestamp(last) if last not in ['unknown','unavailable','none'] else 0 %}
          {% set cooldown = (states('input_number.plants_notification_cooldown_hours') | float(3) * 3600) | int %}
          {{ (now().timestamp() - last_ts) > cooldown }}
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Молочай"
          plant_name_latin: "euphorbia_leuconeura"

  # --------------------------------------------------------------------------
  # Освещённость: уведомление (слишком яркий свет / неправильное место)
  # --------------------------------------------------------------------------
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-3"
    alias: "Растение. Молочай: Уведомление об освещенности"
    description: >
      Если освещенность за пределами порога 30 минут подряд,
      ты дома, не старт системы, кулдаун прошёл — скажем, куда переставить.
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_illuminance
        to: "on"
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.last_euphorbia_leuconeura_illuminance_notification') %}
          {% set last_ts = as_timestamp(last) if last not in ['unknown','unavailable','none'] else 0 %}
          {% set cooldown = (states('input_number.plants_notification_cooldown_hours') | float(3) * 3600) | int %}
          {{ (now().timestamp() - last_ts) > cooldown }}
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Молочай"
          plant_name_latin: "euphorbia_leuconeura"

  # --------------------------------------------------------------------------
  # Периодический авточек раз в 6 часов
  # --------------------------------------------------------------------------
  - id: "plant-euphorbia-periodic-check"
    alias: "Растение. Молочай: Периодическая проверка"
    description: >
      Периодически прогоняем общую проверку условий содержания,
      чтобы не пропускать проблемы, если не было явного триггера.
    mode: single
    trigger:
      - platform: time_pattern
        hours: "/6"
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Молочай"
          plant_name_latin: "euphorbia_leuconeura"
