################################################################################
# /packages/plant_euphorbia_leuconeura.yaml
################################################################################
#
# Пакет конфигураций для мониторинга Молочая (Euphorbia leuconeura)
# Использует общие скрипты и логику из пакета plants_common.yaml
#
################################################################################

##############################################################################
#                             ВХОДНЫЕ ПЕРЕМЕННЫЕ
##############################################################################
input_text:
  notification_history_euphorbia_leuconeura:
    name: "Молочай: История уведомлений"

input_datetime:
  last_euphorbia_leuconeura_soil_notification:
    name: "Last Euphorbia Soil Notification Time"
    has_date: true
    has_time: true
    initial: "1970-01-01 00:00:00"
  last_euphorbia_leuconeura_temperature_notification:
    name: "Last Euphorbia Temperature Notification Time"
    has_date: true
    has_time: true
    initial: "1970-01-01 00:00:00"
  last_euphorbia_leuconeura_illuminance_notification:
    name: "Last Euphorbia Illuminance Notification Time"
    has_date: true
    has_time: true
    initial: "1970-01-01 00:00:00"

##############################################################################
#                                 СЕНСОРЫ
##############################################################################
sensor:
  - platform: filter
    name: "euphorbia_leuconeura_filtered_temperature"
    entity_id: sensor.euphorbia_leuconeura_temperature
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2
  - platform: filter
    name: "euphorbia_leuconeura_filtered_air_humidity"
    entity_id: sensor.euphorbia_leuconeura_air_humidity
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2
  - platform: filter
    name: "euphorbia_leuconeura_filtered_soil_moisture"
    entity_id: sensor.euphorbia_leuconeura_soil_moisture
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2
  - platform: filter
    name: "euphorbia_leuconeura_filtered_illuminance"
    entity_id: sensor.euphorbia_leuconeura_illuminance
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2

##############################################################################
#                            БИНАРНЫЕ СЕНСОРЫ
##############################################################################
binary_sensor:
  - platform: template
    sensors:
      plant_alert_euphorbia_leuconeura_soil:
        unique_id: plant_alert_euphorbia_leuconeura_soil
        friendly_name: "Необходимость полива (Молочай)"
        device_class: problem
        availability_template: >-
          {{ states('sensor.euphorbia_leuconeura_filtered_soil_moisture') not in ['unknown','unavailable',''] and
             states('number.euphorbia_leuconeura_min_soil_moisture') not in ['unknown','unavailable',''] }}
        value_template: >-
          {% set moisture = states('sensor.euphorbia_leuconeura_filtered_soil_moisture') | float(0) %}
          {% set min_threshold = states('number.euphorbia_leuconeura_min_soil_moisture') | float(0) %}
          {{ moisture > 0 and moisture < min_threshold }}
      plant_alert_euphorbia_leuconeura_temperature:
        unique_id: plant_alert_euphorbia_leuconeura_temperature
        friendly_name: "Необходимость согрева или охлаждения (Молочай)"
        device_class: problem
        availability_template: >-
          {{ states('sensor.euphorbia_leuconeura_filtered_temperature') not in ['unknown','unavailable',''] and
             states('number.euphorbia_leuconeura_min_temperature') not in ['unknown','unavailable',''] and
             states('number.euphorbia_leuconeura_max_temperature') not in ['unknown','unavailable',''] }}
        value_template: >-
          {% set temperature = states('sensor.euphorbia_leuconeura_filtered_temperature') | float(0) %}
          {% set min_threshold = states('number.euphorbia_leuconeura_min_temperature') | float(0) %}
          {% set max_threshold = states('number.euphorbia_leuconeura_max_temperature') | float(0) %}
          {{ (temperature > 0 and temperature < min_threshold) or (temperature > max_threshold) }}
      plant_alert_euphorbia_leuconeura_illuminance:
        unique_id: plant_alert_euphorbia_leuconeura_illuminance
        friendly_name: "Необходимость коррекции освещенности (Молочай)"
        device_class: problem
        availability_template: >-
          {{ states('sensor.euphorbia_leuconeura_filtered_illuminance') not in ['unknown','unavailable',''] and
             states('number.euphorbia_leuconeura_max_illuminance') not in ['unknown','unavailable',''] }}
        value_template: >-
          {% set illuminance = states('sensor.euphorbia_leuconeura_filtered_illuminance') | float(0) %}
          {% set max_threshold = states('number.euphorbia_leuconeura_max_illuminance') | float(0) %}
          {{ illuminance > 0 and illuminance > max_threshold }}
        # Если нужно реагировать и на недостаток света:
        # {{ (illuminance > 0 and illuminance < min_threshold) or (illuminance > max_threshold) }}

##############################################################################
#                              АВТОМАТИЗАЦИИ
##############################################################################
automation:
  # Полив (домой + кулдаун)
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-1"
    alias: "Растение. Молочай: Уведомление о поливе"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_soil
        to: "on"
    condition:
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.last_euphorbia_leuconeura_soil_notification') %}
          {% set last_ts = as_timestamp(last) if last not in ['unknown','unavailable','none'] else 0 %}
          {% set cooldown = (states('input_number.plants_notification_cooldown_hours') | float(3) * 3600) | int %}
          {{ (now().timestamp() - last_ts) > cooldown }}
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Молочай"
          plant_name_latin: "euphorbia_leuconeura"

  # Температура (домой + кулдаун)
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-2"
    alias: "Растение. Молочай: Уведомление о температуре"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_temperature
        to: "on"
    condition:
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.last_euphorbia_leuconeura_temperature_notification') %}
          {% set last_ts = as_timestamp(last) if last not in ['unknown','unavailable','none'] else 0 %}
          {% set cooldown = (states('input_number.plants_notification_cooldown_hours') | float(3) * 3600) | int %}
          {{ (now().timestamp() - last_ts) > cooldown }}
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Молочай"
          plant_name_latin: "euphorbia_leuconeura"

  # Освещённость (домой + кулдаун)
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-3"
    alias: "Растение. Молочай: Уведомление об освещенности"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_illuminance
        to: "on"
    condition:
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.last_euphorbia_leuconeura_illuminance_notification') %}
          {% set last_ts = as_timestamp(last) if last not in ['unknown','unavailable','none'] else 0 %}
          {% set cooldown = (states('input_number.plants_notification_cooldown_hours') | float(3) * 3600) | int %}
          {{ (now().timestamp() - last_ts) > cooldown }}
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Молочай"
          plant_name_latin: "euphorbia_leuconeura"

  # Периодическая проверка (каждые 6 часов)
  - id: "plant-euphorbia-periodic-check"
    alias: "Растение. Молочай: Периодическая проверка"
    mode: single
    trigger:
      - platform: time_pattern
        hours: "/6"
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Молочай"
          plant_name_latin: "euphorbia_leuconeura"
