################################################################################
# /packages/plant_ficus_lyrata.yaml
################################################################################
#
# Пакет конфигураций для мониторинга Фикуса лировидного (Ficus lyrata)
# Использует общие скрипты и логику из пакета plants_common.yaml
#
################################################################################

##############################################################################
#                             ВХОДНЫЕ ПЕРЕМЕННЫЕ
##############################################################################
input_text:
  notification_history_ficus_lyrata:
    name: "Фикус лировидный: История уведомлений"

input_datetime:
  last_ficus_lyrata_soil_notification:
    name: "Last Ficus lyrata Soil Notification Time"
    has_date: true
    has_time: true
    initial: "1970-01-01 00:00:00"
  last_ficus_lyrata_temperature_notification:
    name: "Last Ficus lyrata Temperature Notification Time"
    has_date: true
    has_time: true
    initial: "1970-01-01 00:00:00"

##############################################################################
#                                 СЕНСОРЫ
##############################################################################
sensor:
  - platform: filter
    name: "ficus_lyrata_filtered_temperature"
    entity_id: sensor.ficus_lyrata_temperature
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2
  - platform: filter
    name: "ficus_lyrata_filtered_air_humidity"
    entity_id: sensor.ficus_lyrata_air_humidity
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2
  - platform: filter
    name: "ficus_lyrata_filtered_soil_moisture"
    entity_id: sensor.ficus_lyrata_soil_moisture
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2

##############################################################################
#                            БИНАРНЫЕ СЕНСОРЫ
##############################################################################
binary_sensor:
  - platform: template
    sensors:
      plant_alert_ficus_lyrata_soil:
        unique_id: plant_alert_ficus_lyrata_soil
        friendly_name: "Необходимость полива (Фикус лировидный)"
        device_class: problem
        availability_template: >-
          {{ states('sensor.ficus_lyrata_filtered_soil_moisture') not in ['unknown','unavailable',''] and
             states('number.ficus_lyrata_min_soil_moisture') not in ['unknown','unavailable',''] }}
        value_template: >-
          {% set moisture = states('sensor.ficus_lyrata_filtered_soil_moisture') | float(0) %}
          {% set min_threshold = states('number.ficus_lyrata_min_soil_moisture') | float(0) %}
          {{ moisture > 0 and moisture < min_threshold }}
      plant_alert_ficus_lyrata_temperature:
        unique_id: plant_alert_ficus_lyrata_temperature
        friendly_name: "Необходимость согрева или охлаждения (Фикус лировидный)"
        device_class: problem
        availability_template: >-
          {{ states('sensor.ficus_lyrata_filtered_temperature') not in ['unknown','unavailable',''] and
             states('number.ficus_lyrata_min_temperature') not in ['unknown','unavailable',''] and
             states('number.ficus_lyrata_max_temperature') not in ['unknown','unavailable',''] }}
        value_template: >-
          {% set temperature = states('sensor.ficus_lyrata_filtered_temperature') | float(0) %}
          {% set min_threshold = states('number.ficus_lyrata_min_temperature') | float(0) %}
          {% set max_threshold = states('number.ficus_lyrata_max_temperature') | float(0) %}
          {{ (temperature > 0 and temperature < min_threshold) or (temperature > max_threshold) }}

##############################################################################
#                              АВТОМАТИЗАЦИИ
##############################################################################
automation:
  # Полив (домой + кулдаун)
  - id: "3ee8085c-621a-49f0-98f6-cce0d5c3c49b"
    alias: "Растение. Фикус лировидный: Уведомление о поливе"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_ficus_lyrata_soil
        to: "on"
    condition:
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.last_ficus_lyrata_soil_notification') %}
          {% set last_ts = as_timestamp(last) if last not in ['unknown','unavailable','none'] else 0 %}
          {% set cooldown = (states('input_number.plants_notification_cooldown_hours') | float(3) * 3600) | int %}
          {{ (now().timestamp() - last_ts) > cooldown }}
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Фикус лировидный"
          plant_name_latin: "ficus_lyrata"

  # Температура (домой + кулдаун)
  - id: "3ee8085c-621a-49f0-98f6-cce0d5c3c49c"
    alias: "Растение. Фикус лировидный: Уведомление о температуре"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_ficus_lyrata_temperature
        to: "on"
    condition:
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.last_ficus_lyrata_temperature_notification') %}
          {% set last_ts = as_timestamp(last) if last not in ['unknown','unavailable','none'] else 0 %}
          {% set cooldown = (states('input_number.plants_notification_cooldown_hours') | float(3) * 3600) | int %}
          {{ (now().timestamp() - last_ts) > cooldown }}
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Фикус лировидный"
          plant_name_latin: "ficus_lyrata"

  # Периодическая проверка (каждые 6 часов)
  - id: "plant-ficus-periodic-check"
    alias: "Растение. Фикус лировидный: Периодическая проверка"
    mode: single
    trigger:
      - platform: time_pattern
        hours: "/6"
    action:
      - service: script.plant_check_conditions
        data:
          plant_name: "Фикус лировидный"
          plant_name_latin: "ficus_lyrata"
