# /packages/plant_euphorbia_leuconeura.yaml #
############################################

# Этот пакет конфигураций Home Assistant предназначен для мониторинга условий
# содержания растения Молочай (Euphorbia leuconeura) и включает в себя механизмы
# уведомлений о необходимости ухода. Пакет обеспечивает контроль за температурой,
# влажностью воздуха и почвы, а также освещенностью, отправляя уведомления, если
# условия выходят за допустимые пределы.

# Конфигурации
# Входные Тексты и Даты

# История уведомлений Молочай: Хранит историю отправленных уведомлений о
# состоянии растения.

# Справочно по сенсорам:
# sensor.euphorbia_leuconeura_temperature - фактическая температура
# number.euphorbia_leuconeura_min_temperature - минимально допустимая температура
# number.euphorbia_leuconeura_max_temperature - максимально допустимая температура
# sensor.euphorbia_leuconeura_air_humidity - фактическая влажность воздуха
# number.euphorbia_leuconeura_min_air_humidity - минимально допустимая влажность воздуха
# number.euphorbia_leuconeura_max_air_humidity - максимально допустимая влажность воздуха
# sensor.euphorbia_leuconeura_soil_moisture - фактическая влажность почвы
# number.euphorbia_leuconeura_min_soil_moisture - минимально допустимая влажность почвы
# number.euphorbia_leuconeura_max_soil_moisture - максимально допустимая влажность почвы
# sensor.euphorbia_leuconeura_illuminance - фактическая освещенность
# number.euphorbia_leuconeura_min_illuminance - минимально допустимая освещенность
# number.euphorbia_leuconeura_max_illuminance - максимально допустимая освещенность

# Усредненные значения для устранения ложных срабатываний:
# sensor.euphorbia_leuconeura_filtered_temperature - усредненная температура
# sensor.euphorbia_leuconeura_filtered_air_humidity - усредненная влажность воздуха
# sensor.euphorbia_leuconeura_filtered_soil_moisture - усредненная влажность почвы
# sensor.euphorbia_leuconeura_filtered_illuminance - усредненная освещенность

# Бинарные датчики:
# binary_sensor.plant_alert_euphorbia_leuconeura_soil - сигнализирует о необходимости полива
# binary_sensor.plant_alert_euphorbia_leuconeura_temperature - сигнализирует о недопустимой температуре
# binary_sensor.plant_alert_euphorbia_leuconeura_illuminance - сигнализирует о недопустимой освещенности
# binary_sensor.euphorbia_watering_needed_recently - указывает на необходимость полива в последнее время

# Таймер:
# timer.euphorbia_watering_alert - используется для сброса тревоги о поливе

# Автоматизации:
# automation.euphorbia_watering_alert_reset - сбрасывает тревогу о поливе
# automation.euphorbia_watering_notification - отправляет уведомление о необходимости полива
# automation.euphorbia_temperature_notification - отправляет уведомление о недопустимой температуре
# automation.euphorbia_illuminance_notification - отправляет уведомление о недопустимой освещенности

# Условия и уведомления:
# Уведомления отправляются только в том случае, если с момента последнего уведомления
# прошло более 3 часов (10800 секунд). Это предотвращает частые повторные уведомления.
# Уведомления отправляются только в присутствии пользователя дома (person.master или person.tatiana).

# Усредненные значения для устранения ложных срабатываний
sensor:
  - platform: filter
    name: "euphorbia_leuconeura_filtered_temperature"
    entity_id: sensor.euphorbia_leuconeura_temperature
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2
  - platform: filter
    name: "euphorbia_leuconeura_filtered_air_humidity"
    entity_id: sensor.euphorbia_leuconeura_air_humidity
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2
  - platform: filter
    name: "euphorbia_leuconeura_filtered_soil_moisture"
    entity_id: sensor.euphorbia_leuconeura_soil_moisture
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2
  - platform: filter
    name: "euphorbia_leuconeura_filtered_illuminance"
    entity_id: sensor.euphorbia_leuconeura_illuminance
    filters:
      - filter: time_simple_moving_average
        window_size: "01:00"
        precision: 2

input_text:
  notification_history_euphorbia:
    name: "Молочай: История уведомлений"

# Время последнего уведомления о влажности и температуре почвы:
# Записывает момент отправки последнего уведомления о необходимости полива
# и обеспечения тепла.
input_datetime:
  last_euphorbia_soil_notification:
    name: "Last Euphorbia Soil Notification Time"
    has_date: true
    has_time: true
  last_euphorbia_temperature_notification:
    name: "Last Euphorbia Temperature Notification Time"
    has_date: true
    has_time: true
  last_euphorbia_illuminance_notification:
    name: "Last Euphorbia Illuminance Notification Time"
    has_date: true
    has_time: true

# Механизм установления отметок об отправке уведомлений включает в себя
# обновление input_datetime со временем последнего уведомления.
# Это обеспечивает контроль за частотой уведомлений и предотвращает их
# избыточность, повышая эффективность коммуникации с пользователем и
# внимание к актуальным потребностям растения.

# Бинарные Датчики

binary_sensor:
  - platform: template
    sensors:
      # Необходимость полива (Молочай): Активируется, когда влажность почвы
      # опускается ниже заданного порога.
      plant_alert_euphorbia_leuconeura_soil:
        unique_id: plant_alert_euphorbia_leuconeura_soil
        friendly_name: "Необходимость полива (Молочай)"
        device_class: problem
        value_template: >-
          {% set moisture = states('sensor.euphorbia_leuconeura_filtered_soil_moisture') | int(default=0) %}
          {% set min_threshold = states('number.euphorbia_leuconeura_min_soil_moisture') | int(default=0) %}
          {{ moisture > 0 and moisture < min_threshold }}
      # Необходимость согрева или охлаждения (Молочай): Сигнализирует о снижении температуры
      # почвы ниже комфортной для растения или превышении максимально допустимой температуры.
      plant_alert_euphorbia_leuconeura_temperature:
        unique_id: plant_alert_euphorbia_leuconeura_temperature
        friendly_name: "Необходимость согрева или охлаждения (Молочай)"
        device_class: problem
        value_template: >-
          {% set temperature = states('sensor.euphorbia_leuconeura_filtered_temperature') | int(default=0) %}
          {% set min_threshold = states('number.euphorbia_leuconeura_min_temperature') | int(default=0) %}
          {% set max_threshold = states('number.euphorbia_leuconeura_max_temperature') | int(default=0) %}
          {{ (temperature > 0 and temperature < min_threshold) or (temperature > max_threshold) }}
      # Необходимость коррекции освещенности (Молочай): Сигнализирует о снижении освещенности
      # ниже комфортной для растения или превышении максимально допустимой освещенности.
      plant_alert_euphorbia_leuconeura_illuminance:
        unique_id: plant_alert_euphorbia_leuconeura_illuminance
        friendly_name: "Необходимость коррекции освещенности (Молочай)"
        device_class: problem
        value_template: >-
          {% set illuminance = states('sensor.euphorbia_leuconeura_filtered_illuminance') | int(default=0) %}
          {% set min_threshold = states('number.euphorbia_leuconeura_min_illuminance') | int(default=0) %}
          {% set max_threshold = states('number.euphorbia_leuconeura_max_illuminance') | int(default=0) %}
          {{ (illuminance > 0 and illuminance < min_threshold) or (illuminance > max_threshold) }}
      # Euphorbia Needs Watering Recently: Показывает, что растению недавно
      # требовался полив, основываясь на времени последнего уведомления и
      # текущем состоянии датчика влажности.
      euphorbia_watering_needed_recently:
        unique_id: euphorbia_watering_needed_recently
        friendly_name: "Euphorbia Needs Watering Recently"
        value_template: >-
          {% set last_notification = states('input_datetime.last_euphorbia_soil_notification') | default('1970-01-01 00:00:00') %}
          {% set last_notification_ts = as_timestamp(last_notification) %}
          {{ is_state('binary_sensor.plant_alert_euphorbia_leuconeura_soil', 'on') and (as_timestamp(now()) - last_notification_ts) > 10800 }}
        delay_off:
          minutes: 1

# Таймер, который сбрасывает бинарный сенсор через определенное время:
timer:
  euphorbia_watering_alert:
    duration: "01:00:00"

# Автоматизации

automation:
  - id: "a055cc6d-97b2-4bf2-9d7c-ab619bbed005"
    alias: "Молочай: Сброс тревоги о поливе"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.euphorbia_watering_alert
    action:
      - service: homeassistant.turn_off
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_soil

    # Уведомление о необходимости полива
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-1"
    alias: "Растение. Молочай: Уведомление о поливе"
    trigger:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_soil
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: person.master
            state: "home"
          - condition: state
            entity_id: person.tatiana
            state: "home"
      - condition: template
        value_template: >-
          {% set last_notification_ts = as_timestamp(states('input_datetime.last_euphorbia_soil_notification') | default('1970-01-01 00:00:00')) %}
          {{ (as_timestamp(now()) - last_notification_ts) > 10800 }}
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: person.master
                state: "home"
            sequence:
              - service: notify.master
                data:
                  message: "Необходимо полить Молочай: влажность почвы {{ states('sensor.euphorbia_leuconeura_filtered_soil_moisture') }}%."
                  data:
                    photo:
                      file: "/config/www/images/plants_alerts/Euphorbia_leuconeura_soil.webp"
                      caption: "Необходимо полить Молочай!"
          - conditions:
              - condition: state
                entity_id: person.tatiana
                state: "home"
            sequence:
              - service: notify.tatiana
                data:
                  message: "Необходимо полить Молочай: влажность почвы {{ states('sensor.euphorbia_leuconeura_filtered_soil_moisture') }}%."
                  data:
                    photo:
                      file: "/config/www/images/plants_alerts/Euphorbia_leuconeura_soil.webp"
                      caption: "Необходимо полить Молочай!"
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_euphorbia_soil_notification
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      - service: input_text.set_value
        target:
          entity_id: input_text.notification_history_euphorbia
        data: |
          {% set history = states('input_text.notification_history_euphorbia') %}
          {% set new_entry = "Уведомление о поливе Молочая: " + now().strftime('%Y-%m-%d %H:%M:%S') %}
          {{ history + '\n' + new_entry if history|length < 1000 else new_entry }}
      - service: timer.start
        entity_id: timer.euphorbia_watering_alert

  # Уведомление о необходимости тепла
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-2"
    alias: "Растение. Молочай: Уведомление о температуре"
    description: "Отправляет уведомления о необходимости изменения температуры для Молочая, если кто-то есть дома."
    triggers:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_temperature
        to: "on"
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: person.master
            state: "home"
          - condition: state
            entity_id: person.tatiana
            state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >
          {{ (as_timestamp(now()) - as_timestamp(states('input_datetime.last_euphorbia_temperature_notification') | default(0))) > 10800 }}
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: person.master
                state: "home"
            sequence:
              - action: notify.master
                data_template:
                  message: "Молочай необходимо поставить в тёплое место, температура почвы составляет {{ states('sensor.euphorbia_leuconeura_filtered_temperature') }}°C."
                  data:
                    photo:
                      file: "/config/www/images/plants_alerts/Euphorbia_leuconeura_cold.webp"
                      caption: "Молочай необходимо поставить в тёплое место, температура почвы составляет {{ states('sensor.euphorbia_leuconeura_filtered_temperature') }}°C."
        default:
          - action: notify.tatiana
            data_template:
              message: "Молочай необходимо поставить в тёплое место, температура почвы составляет {{ states('sensor.euphorbia_leuconeura_filtered_temperature') }}°C."
              data:
                photo:
                  file: "/config/www/images/plants_alerts/Euphorbia_leuconeura_cold.webp"
                  caption: "Молочай необходимо поставить в тёплое место, температура почвы составляет {{ states('sensor.euphorbia_leuconeura_filtered_temperature') }}°C."
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_euphorbia_temperature_notification
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      - service: input_text.set_value
        target:
          entity_id: input_text.notification_history_euphorbia
        data: |
          {% set history = states('input_text.notification_history_euphorbia') %}
          {% set new_entry = "Уведомление о температуре Молочая: " + now().strftime('%Y-%m-%d %H:%M:%S') %}
          {{ history + '\n' + new_entry if history|length < 1000 else new_entry }}
    mode: single

  # Уведомление о необходимости коррекции освещенности
  - id: "4370eb06-5640-4c42-adde-b91046f301f4-3"
    alias: "Растение. Молочай: Уведомление об освещенности"
    description: "Отправляет уведомления о необходимости коррекции освещенности для Молочая, если кто-то есть дома."
    triggers:
      - platform: state
        entity_id: binary_sensor.plant_alert_euphorbia_leuconeura_illuminance
        to: "on"
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: person.master
            state: "home"
          - condition: state
            entity_id: person.tatiana
            state: "home"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: template
        value_template: >
          {{ (as_timestamp(now()) - as_timestamp(states('input_datetime.last_euphorbia_illuminance_notification') | default(0))) > 10800 }}
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: person.master
                state: "home"
            sequence:
              - action: notify.master
                data_template:
                  message: "Молочай необходимо переместить в более освещенное место, освещенность составляет {{ states('sensor.euphorbia_leuconeura_filtered_illuminance') }} лк."
                  # data:
                  #   photo:
                  #     file: "/config/www/images/plants_alerts/Euphorbia_leuconeura_dark.webp"
                  #     caption: "Молочай необходимо переместить в более освещенное место, освещенность составляет {{ states('sensor.euphorbia_leuconeura_filtered_illuminance') }} лк."
        default:
          - action: notify.tatiana
            data_template:
              message: "Молочай необходимо переместить в более освещенное место, освещенность составляет {{ states('sensor.euphorbia_leuconeura_filtered_illuminance') }} лк."
              # data:
              #   photo:
              #     file: "/config/www/images/plants_alerts/Euphorbia_leuconeura_dark.webp"
              #     caption: "Молочай необходимо переместить в более освещенное место, освещенность составляет {{ states('sensor.euphorbia_leuconeura_filtered_illuminance') }} лк."
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_euphorbia_illuminance_notification
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      - service: input_text.set_value
        target:
          entity_id: input_text.notification_history_euphorbia
        data: |
          {% set history = states('input_text.notification_history_euphorbia') %}
          {% set new_entry = "Уведомление об освещенности Молочая: " + now().strftime('%Y-%m-%d %H:%M:%S') %}
          {{ history + '\n' + new_entry if history|length < 1000 else new_entry }}
    mode: single
