input_number:
  4_memory_used_percentage_max:
    name: Max Memory Used Percentage
    min: 0
    max: 100
    step: 0.1
    mode: box
  101_memory_used_percentage_max:
    name: Max Memory Used Percentage
    min: 0
    max: 100
    step: 0.1
    mode: box
  102_memory_used_percentage_max:
    name: Max Memory Used Percentage
    min: 0
    max: 100
    step: 0.1
    mode: box
  103_memory_used_percentage_max:
    name: Max Memory Used Percentage
    min: 0
    max: 100
    step: 0.1
    mode: box
  104_memory_used_percentage_max:
    name: Max Memory Used Percentage
    min: 0
    max: 100
    step: 0.1
    mode: box
automation:
  - id: "generic_update_memory_usage"
    alias: "Update Max Memory Used Percentage for all containers"
    trigger:
      platform: state
      entity_id:
        - sensor.lxc_jackett_101_memory_used_percentage
        - sensor.lxc_mariadb_102_memory_used_percentage
        - sensor.lxc_deluge_103_memory_used_percentage
        - sensor.lxc_jellyfin_104_memory_used_percentage
        - sensor.qemu_haos11_4_100_memory_used_percentage
    action:
      - condition: template
        value_template: >
          {{ trigger.to_state is not none and trigger.to_state.state not in ['unknown', 'unavailable'] }}
      - service: input_number.set_value
        data_template:
          entity_id: >
            {{ 'input_number.' ~ trigger.entity_id.split('_')[2] ~ '_memory_used_percentage_max' }}
          value: >
            {% set current = trigger.to_state.state | float(default=0) %}
            {% set max = states('input_number.' ~ trigger.entity_id.split('_')[2] ~ '_memory_used_percentage_max') | float(default=0) %}
            {{ [current, max] | max }}
      - condition: template
        value_template: >
          {{ trigger.to_state is not none and trigger.to_state.state | float(default=0) >= 97 }}
      - service: notify.master
        data_template:
          message: >
            {{ trigger.to_state.attributes.friendly_name }} memory usage is at {{ trigger.to_state.state | float(default=0) }}%, which is near or at capacity.
