################################################################################
# /packages/room_livingroom.yaml
################################################################################
#
# УПРАВЛЕНИЕ ОСВЕЩЕНИЕМ В ГОСТИНОЙ
#
# УСТРОЙСТВА:
# • Бра (light.livingroom_scone_dimmer)
# • Люстра (light.livingroom_main_switch_left)
# • Правый свет (light.livingroom_main_switch_right)
#
# УПРАВЛЕНИЕ:
# • MQTT-выключатель (device_id: 719cda594198c3eafa3817b9230f2afa)
#   - Кнопка 3 (одиночное) → люстра
#   - Кнопка 4 (одиночное) → бра
#   - Кнопка 4 (двойное) → правый свет
#
# ЗАВИСИМОСТИ:
# • helper_climate_common.yaml — усреднённые датчики температуры/влажности
#   (sensor.livingroom_average_temperature, sensor.livingroom_average_humidity)
#
################################################################################

##############################################################################
#                             АВТОМАТИЗАЦИИ
##############################################################################

automation:
  # ==========================================================================
  # УПРАВЛЕНИЕ ОСВЕЩЕНИЕМ С MQTT-ВЫКЛЮЧАТЕЛЯ
  # ==========================================================================

  # --------------------------------------------------------------------------
  # Переключение бра (кнопка 4, одиночное нажатие)
  # --------------------------------------------------------------------------
  - id: "9fff2de3-f169-4fda-8a8a-91966fc51f13"
    alias: "Гостиная: переключение бра (кнопка 4, одиночное нажатие)"
    description: >
      Переключает бра в гостиной при одиночном нажатии кнопки 4.

      ТРИГГЕР:
      • MQTT-выключатель (device_id: 719cda594198c3eafa3817b9230f2afa)
      • Кнопка 4, одиночное нажатие (subtype: 4_single)

      ДЕЙСТВИЕ:
      • Переключает свет (ON → OFF / OFF → ON)
      • light.livingroom_scone_dimmer

      РЕЖИМ:
      • restart — новое нажатие прерывает предыдущее действие
      • Защита от случайных двойных нажатий

      НАЗНАЧЕНИЕ:
      • Удобное управление локальным освещением
      • Не требует доступа к смартфону
      • Работает даже при недоступности Home Assistant
    mode: restart
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 719cda594198c3eafa3817b9230f2afa
        type: action
        subtype: 4_single
    actions:
      - action: light.toggle
        target:
          entity_id: light.livingroom_scone_dimmer
      # Логирование
      - action: script.log_helper_event
        data:
          level: info
          message: "Гостиная: переключение бра (кнопка 4, одиночное нажатие)."
          source: "{{ this.entity_id }}"
          trigger_entity: "{{ trigger.entity_id | default('') }}"
          trigger_from: >-
            {{ trigger.from_state.state
               if trigger is defined and trigger.from_state is not none
               else '' }}
          trigger_to: >-
            {{ trigger.to_state.state
               if trigger is defined and trigger.to_state is not none
               else '' }}
          extra: >-
            bra={{ states('light.livingroom_scone_dimmer') }}
  # --------------------------------------------------------------------------
  # Переключение люстры (кнопка 3, одиночное нажатие)
  # --------------------------------------------------------------------------
  - id: "54ea7c3d-a37d-4ce4-80ff-f2da00a450c2"
    alias: "Гостиная: переключение люстры (кнопка 3, одиночное нажатие)"
    description: >
      Переключает основную люстру в гостиной при одиночном нажатии кнопки 3.

      ТРИГГЕР:
      • MQTT-выключатель (device_id: 719cda594198c3eafa3817b9230f2afa)
      • Кнопка 3, одиночное нажатие (subtype: 3_single)

      ДЕЙСТВИЕ:
      • Переключает основное освещение (ON → OFF / OFF → ON)
      • light.livingroom_main_switch_left

      РЕЖИМ:
      • restart — новое нажатие прерывает предыдущее действие

      НАЗНАЧЕНИЕ:
      • Основное освещение комнаты
      • Наиболее часто используемая кнопка
      • Интуитивное расположение (центральная кнопка)
    mode: restart
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 719cda594198c3eafa3817b9230f2afa
        type: action
        subtype: 3_single
    actions:
      - action: light.toggle
        target:
          entity_id: light.livingroom_main_switch_left
      # Логирование
      - action: script.log_helper_event
        data:
          level: info
          message: "Гостиная: переключение люстры (кнопка 3, одиночное нажатие)."
          source: "{{ this.entity_id }}"
          trigger_entity: "{{ trigger.entity_id | default('') }}"
          trigger_from: >-
            {{ trigger.from_state.state
               if trigger is defined and trigger.from_state is not none
               else '' }}
          trigger_to: >-
            {{ trigger.to_state.state
               if trigger is defined and trigger.to_state is not none
               else '' }}
          extra: >-
            chandelier={{ states('light.livingroom_main_switch_left') }}
  # --------------------------------------------------------------------------
  # Переключение правого света (кнопка 4, двойное нажатие)
  # --------------------------------------------------------------------------
  - id: "916eb0c3-eee6-409d-9ce2-4dc00c9f7051"
    alias: "Гостиная: переключение правого света (кнопка 4, двойное нажатие)"
    description: >
      Переключает правый свет в гостиной при двойном нажатии кнопки 4.

      ТРИГГЕР:
      • MQTT-выключатель (device_id: 719cda594198c3eafa3817b9230f2afa)
      • Кнопка 4, двойное нажатие (subtype: 4_double)

      ДЕЙСТВИЕ:
      • Переключает дополнительное освещение (ON → OFF / OFF → ON)
      • light.livingroom_main_switch_right

      РЕЖИМ:
      • restart — новое нажатие прерывает предыдущее действие

      НАЗНАЧЕНИЕ:
      • Дополнительное/акцентное освещение
      • Двойное нажатие — защита от случайного переключения
      • Используется реже основного света

      ПРИМЕЧАНИЕ:
      • Двойное нажатие той же кнопки, что и бра (кнопка 4)
      • Одиночное → бра, двойное → правый свет
    mode: restart
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 719cda594198c3eafa3817b9230f2afa
        type: action
        subtype: 4_double
    actions:
      - action: light.toggle
        target:
          entity_id: light.livingroom_main_switch_right
      # Логирование
      - action: script.log_helper_event
        data:
          level: info
          message: "Гостиная: переключение правого света (кнопка 4, двойное нажатие)."
          source: "{{ this.entity_id }}"
          trigger_entity: "{{ trigger.entity_id | default('') }}"
          trigger_from: >-
            {{ trigger.from_state.state
               if trigger is defined and trigger.from_state is not none
               else '' }}
          trigger_to: >-
            {{ trigger.to_state.state
               if trigger is defined and trigger.to_state is not none
               else '' }}
          extra: >-
            right={{ states('light.livingroom_main_switch_right') }}
