################################################################################
# /packages/room_livingroom_air_purifier.yaml
################################################################################
#
# АВТОМАТИЧЕСКОЕ УПРАВЛЕНИЕ ОЧИСТИТЕЛЕМ ВОЗДУХА В ГОСТИНОЙ
#
# ЛОГИКА:
# • Источник данных: sensor.zhimi_cn_271517251_mb3_pm2_5_density_p_3_6
# • Сглаживание: statistics (mean за 5 мин, 120 сэмплов)
# • Включение: PM2.5 > 20 µg/m³ стабильно 5 мин
# • Выключение: PM2.5 < 10 µg/m³ стабильно 5 мин
# • Гистерезис: работающий остаётся ON, пока PM2.5 > 10
# • Антидребезг: мин. время работы/простоя (10/15 мин)
#
# УСТРОЙСТВО:
# • fan.zhimi_cn_271517251_mb3_s_2_air_purifier
#
# ЗАВИСИМОСТИ:
# • helper_climate_common.yaml — таймеры, скрипт обновления
#
################################################################################

##############################################################################
#                           ВХОДНЫЕ ПЕРЕМЕННЫЕ
##############################################################################

input_boolean:
  # --------------------------------------------------------------------------
  # Автоматический режим очистителя
  # --------------------------------------------------------------------------
  # Мастер-переключатель автоматизации очистителя воздуха.
  # OFF → очиститель управляется только вручную
  # ON → автоматическое управление на основе PM2.5
  livingroom_air_purifier_auto:
    name: "Гостиная: авто-режим очистителя"
    icon: mdi:autorenew
    initial: true

input_number:
  # --------------------------------------------------------------------------
  # Нижний порог PM2.5 (µg/m³)
  # --------------------------------------------------------------------------
  # Мягкий порог для гистерезиса.
  # Очиститель выключается, когда PM2.5 < этого значения стабильно 5 мин.
  # Работающий очиститель остаётся ON, пока PM2.5 > этого порога.
  livingroom_pm25_low:
    name: "Гостиная: нижний порог PM2.5 (µg/m³)"
    min: 0
    max: 75
    step: 1
    initial: 10
    unit_of_measurement: "µg/m³"

  # --------------------------------------------------------------------------
  # Верхний порог PM2.5 (µg/m³)
  # --------------------------------------------------------------------------
  # Жёсткий порог для включения.
  # Очиститель включается, когда PM2.5 > этого значения стабильно 5 мин.
  livingroom_pm25_high:
    name: "Гостиная: верхний порог PM2.5 (µg/m³)"
    min: 5
    max: 100
    step: 1
    initial: 20
    unit_of_measurement: "µg/m³"

  # --------------------------------------------------------------------------
  # Минимальное время работы (мин)
  # --------------------------------------------------------------------------
  # Антидребезг: очиститель не выключится раньше этого времени.
  # Предотвращает частые включения/выключения при колебаниях PM2.5.
  livingroom_air_min_on_min:
    name: "Очиститель: мин. время работы (мин)"
    min: 1
    max: 120
    step: 1
    initial: 10

  # --------------------------------------------------------------------------
  # Минимальное время простоя (мин)
  # --------------------------------------------------------------------------
  # Антидребезг: очиститель не включится раньше этого времени.
  # Предотвращает износ устройства от частых запусков.
  livingroom_air_min_off_min:
    name: "Очиститель: мин. время простоя (мин)"
    min: 1
    max: 120
    step: 1
    initial: 15

##############################################################################
#                               СЕНСОРЫ
##############################################################################

sensor:
  # --------------------------------------------------------------------------
  # Усреднённое значение PM2.5
  # --------------------------------------------------------------------------
  # Статистический сенсор для сглаживания колебаний PM2.5.
  #
  # Параметры:
  # • state_characteristic: mean — среднее арифметическое
  # • sampling_size: 120 — количество сэмплов для расчёта
  # • max_age: 5 мин — максимальный возраст данных
  # • precision: 1 — один знак после запятой
  #
  # Назначение:
  # • Фильтрация краткосрочных всплесков PM2.5
  # • Предотвращение ложных срабатываний
  # • Более стабильное управление очистителем
  - platform: statistics
    name: "Living Room PM2.5 Avg"
    unique_id: living_room_pm25_avg
    entity_id: sensor.zhimi_cn_271517251_mb3_pm2_5_density_p_3_6
    state_characteristic: mean
    sampling_size: 120
    max_age:
      minutes: 5
    precision: 1

##############################################################################
#                               БИНАРНЫЕ СЕНСОРЫ
##############################################################################

binary_sensor:
  - platform: template
    sensors:
      # ------------------------------------------------------------------------
      # Необходимость очистки воздуха (гистерезис)
      # ------------------------------------------------------------------------
      # Вычисляет, нужно ли включить/выключить очиститель воздуха.
      #
      # ЛОГИКА ГИСТЕРЕЗИСА:
      # • Выключен → включается при PM2.5 > 20 µg/m³
      # • Включён → остаётся ON, пока PM2.5 > 10 µg/m³
      # • Включён → выключается при PM2.5 ≤ 10 µg/m³
      #
      # ПРИОРИТЕТ ДАННЫХ:
      # 1. Усреднённое значение (sensor.living_room_pm25_avg)
      # 2. Сырое значение (sensor.zhimi_cn_271517251_mb3_pm2_5_density_p_3_6)
      #
      # ЗАЩИТА ОТ ОШИБОК:
      # • Если оба датчика недоступны → сохраняет предыдущее состояние
      # • Валидация порогов: high всегда > low
      #
      # ИКОНКА:
      # • ON → mdi:air-filter (требуется очистка)
      # • OFF → mdi:check-circle-outline (воздух чистый)
      livingroom_need_air_purify:
        unique_id: livingroom_need_air_purify
        friendly_name: "Гостиная: нужна очистка воздуха"
        device_class: problem
        icon_template: >-
          {% if is_state('binary_sensor.livingroom_need_air_purify', 'on') %}
            mdi:air-filter
          {% else %}
            mdi:check-circle-outline
          {% endif %}

        availability_template: >-
          {{ states('sensor.zhimi_cn_271517251_mb3_pm2_5_density_p_3_6') not in ['unknown','unavailable',''] }}

        value_template: >-
          {% set pm_raw = states('sensor.zhimi_cn_271517251_mb3_pm2_5_density_p_3_6') | float(default=none) %}
          {% set pm_avg = states('sensor.living_room_pm2_5_avg') | float(default=none) %}
          {% set pm = pm_avg if pm_avg is not none else pm_raw %}
          {% if pm is none %}
            {{ states('binary_sensor.livingroom_need_air_purify') }}
          {% else %}
            {% set low  = states('input_number.livingroom_pm25_low')  | float(10) %}
            {% set high = states('input_number.livingroom_pm25_high') | float(20) %}
            {% if low >= high %}{% set high = low + 1 %}{% endif %}
            {% set was_on = is_state('binary_sensor.livingroom_need_air_purify','on') %}
            {% if was_on %}
              {{ pm > low }}
            {% else %}
              {{ pm > high }}
            {% endif %}
          {% endif %}

##############################################################################
#                              АВТОМАТИЗАЦИИ
##############################################################################

automation:
  # ==========================================================================
  # АВТОМАТИЧЕСКОЕ УПРАВЛЕНИЕ ОЧИСТИТЕЛЕМ
  # ==========================================================================

  # --------------------------------------------------------------------------
  # Включение очистителя при загрязнении воздуха
  # --------------------------------------------------------------------------
  - id: "7b7b1b1a-2f7a-4c67-8ccf-7c3b0c5f2d11"
    alias: "Гостиная: включить очиститель"
    description: >
      Включает очиститель воздуха при превышении порога PM2.5.

      ТРИГГЕР:
      • binary_sensor.livingroom_need_air_purify: OFF → ON стабильно 5 мин
      • PM2.5 > 20 µg/m³ (верхний порог)

      УСЛОВИЯ:
      1. Автоматический режим включён (livingroom_air_purifier_auto = ON)
      2. Минимальное время простоя прошло (≥15 мин с последнего выключения)

      ЗАЩИТА ОТ ЧАСТЫХ ВКЛЮЧЕНИЙ:
      • Триггер с задержкой 5 мин → защита от кратковременных всплесков
      • Проверка времени простоя → защита от износа устройства

      ДЕЙСТВИЕ:
      • Включает fan.zhimi_cn_271517251_mb3_s_2_air_purifier
      • Обновляет input_datetime.air_purifier_last_on (через helper_climate_common)
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_need_air_purify
        from: "off"
        to: "on"
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.livingroom_air_purifier_auto
        state: "on"
      - condition: template
        value_template: >-
          {% set last_off = states('input_datetime.air_purifier_last_off') %}
          {% if last_off in ['unknown','unavailable'] %}
            true
          {% else %}
            {% set minutes_off = (as_timestamp(now()) - as_timestamp(last_off)) / 60 %}
            {{ minutes_off >= states('input_number.livingroom_air_min_off_min') | int }}
          {% endif %}
    action:
      - service: fan.turn_on
        target:
          entity_id: fan.zhimi_cn_271517251_mb3_s_2_air_purifier

  # --------------------------------------------------------------------------
  # Выключение очистителя при улучшении качества воздуха
  # --------------------------------------------------------------------------
  - id: "e0d6d9f3-0c1c-4822-9b05-ea2e7e2f0b5c"
    alias: "Гостиная: выключить очиститель"
    description: >
      Выключает очиститель воздуха при нормализации PM2.5.

      ТРИГГЕР:
      • binary_sensor.livingroom_need_air_purify: ON → OFF стабильно 5 мин
      • PM2.5 ≤ 10 µg/m³ (нижний порог)

      УСЛОВИЯ:
      1. Автоматический режим включён (livingroom_air_purifier_auto = ON)
      2. Минимальное время работы прошло (≥10 мин с последнего включения)

      ЗАЩИТА ОТ ЧАСТЫХ ВЫКЛЮЧЕНИЙ:
      • Триггер с задержкой 5 мин → защита от кратковременного улучшения
      • Проверка времени работы → гарантия эффективной очистки

      ГИСТЕРЕЗИС:
      • Включается при PM2.5 > 20 µg/m³
      • Выключается при PM2.5 ≤ 10 µg/m³
      • Зона стабильности: 10–20 µg/m³

      ДЕЙСТВИЕ:
      • Выключает fan.zhimi_cn_271517251_mb3_s_2_air_purifier
      • Обновляет input_datetime.air_purifier_last_off (через helper_climate_common)
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_need_air_purify
        from: "on"
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.livingroom_air_purifier_auto
        state: "on"
      - condition: template
        value_template: >-
          {% set last_on = states('input_datetime.air_purifier_last_on') %}
          {% if last_on in ['unknown','unavailable'] %}
            true
          {% else %}
            {% set minutes_on = (as_timestamp(now()) - as_timestamp(last_on)) / 60 %}
            {{ minutes_on >= states('input_number.livingroom_air_min_on_min') | int }}
          {% endif %}
    action:
      - service: fan.turn_off
        target:
          entity_id: fan.zhimi_cn_271517251_mb3_s_2_air_purifier

  # ==========================================================================
  # ТЕХНИЧЕСКИЕ ТРИГГЕРЫ ДЛЯ УВЕДОМЛЕНИЙ
  # ==========================================================================

  # --------------------------------------------------------------------------
  # Триггер: фильтр очистителя <10%
  # --------------------------------------------------------------------------
  - id: "a4596f3c-27bf-48a8-a6db-62f9905f12fd"
    alias: "Триггер: фильтр очистителя <10%"
    description: >
      Технический триггер для уведомлений о необходимости замены фильтра.

      ТРИГГЕР:
      • sensor.zhimi_cn_271517251_mb3_filter_life_level_p_4_3 < 10% стабильно 1 мин

      НАЗНАЧЕНИЕ:
      • Активирует сенсор в других пакетах (например, notifications.yaml)
      • Не выполняет действий напрямую (actions: [])

      ИСПОЛЬЗОВАНИЕ:
      • В других автоматизациях можно отслеживать последний триггер этой автоматизации
      • Позволяет централизованно управлять уведомлениями
    triggers:
      - trigger: numeric_state
        entity_id: sensor.zhimi_cn_271517251_mb3_filter_life_level_p_4_3
        below: 10
        for: "00:01:00"
    actions: []

  # --------------------------------------------------------------------------
  # Триггер: фильтр очистителя >10%
  # --------------------------------------------------------------------------
  - id: "373bc4e2-1993-46df-85c5-0ff0470a1630"
    alias: "Триггер: фильтр очистителя >10%"
    description: >
      Технический триггер для сброса уведомлений о замене фильтра.

      ТРИГГЕР:
      • sensor.zhimi_cn_271517251_mb3_filter_life_level_p_4_3 > 10% стабильно 1 мин

      НАЗНАЧЕНИЕ:
      • Сбрасывает флаг air_filter_replace_notified в других пакетах
      • Позволяет повторно уведомить при следующем износе фильтра

      ИСПОЛЬЗОВАНИЕ:
      • После замены фильтра уровень > 10% → триггер сбрасывает уведомление
      • При следующем износе < 10% → уведомление снова отправляется
    triggers:
      - trigger: numeric_state
        entity_id: sensor.zhimi_cn_271517251_mb3_filter_life_level_p_4_3
        above: 10
        for: "00:01:00"
    actions: []
