################################################################################
# /packages/room_bathroom_lights.yaml
################################################################################
#
# Пакет конфигураций для освещения в ванной комнате.
# Содержит настройки светильников, группы освещения и автоматизации для управления
# яркостью, реакцией на движение, режимами работы и таймерами отключения.
#
################################################################################

##############################################################################
#                                  ОСВЕЩЕНИЕ
##############################################################################
light:
  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_r1_philips
    host: !secret bathroom_spot_r1_ip
    token: !secret bathroom_spot_r1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_r2_philips
    host: !secret bathroom_spot_r2_ip
    token: !secret bathroom_spot_r2_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_l1_philips
    host: !secret bathroom_spot_l1_ip
    token: !secret bathroom_spot_l1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_c1_philips
    host: !secret bathroom_spot_c1_ip
    token: !secret bathroom_spot_c1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_c2_philips
    host: !secret bathroom_spot_c2_ip
    token: !secret bathroom_spot_c2_token
    model: philips.light.downlight

##############################################################################
#                                   ГРУППЫ
##############################################################################
group:
  bathroom_all_lights:
    name: "Все светильники ванной"
    entities:
      - light.bathroom_spot_r1_philips
      - light.bathroom_spot_r2_philips
      - light.bathroom_spot_l1_philips
      - light.bathroom_spot_c1_philips
      - light.bathroom_spot_c2_philips
      - light.bathroom_relay_l2

  bathroom_spots:
    name: "Точечные светильники ванной"
    entities:
      - light.bathroom_spot_r1_philips
      - light.bathroom_spot_r2_philips
      - light.bathroom_spot_l1_philips
      - light.bathroom_spot_c1_philips
      - light.bathroom_spot_c2_philips

  bathroom_night_lights:
    name: "Ночное освещение ванной"
    entities:
      - light.bathroom_spot_l1_philips

##############################################################################
#                             ВСПОМОГАТЕЛЬНЫЕ СЕНСОРЫ
##############################################################################
binary_sensor:
  - platform: template
    sensors:
      is_night_mode:
        friendly_name: "Ночной режим освещения"
        value_template: "{{ now().hour >= 22 or now().hour < 6 }}"

##############################################################################
#                                ТАЙМЕРЫ
##############################################################################
timer:
  timer_bathroom:
    name: "Движение отсутствует"
    duration: "00:03:00"

##############################################################################
#                                СКРИПТЫ
##############################################################################
script:
  bathroom_toggle_night_mode:
    alias: "Переключение ночного режима в ванной"
    sequence:
      # Проверяем, включен ли хотя бы один светильник из ночной группы
      - if:
          condition: or
          conditions:
            - condition: state
              entity_id: light.bathroom_spot_l1_philips
              state: "on"
            - condition: state
              entity_id: light.bathroom_relay_l2
              state: "on"
        then:
          # Если включен - выключаем все
          - service: light.turn_off
            target:
              entity_id: group.bathroom_all_lights
        else:
          - service: light.turn_on
            target:
              entity_id: light.bathroom_spot_l1_philips
            data:
              brightness_pct: 10
          - service: timer.start
            target:
              entity_id: timer.timer_bathroom

  bathroom_toggle_day_mode:
    alias: "Переключение дневного режима в ванной"
    sequence:
      # Проверяем, включен ли хотя бы один светильник
      - if:
          condition: state
          entity_id: group.bathroom_all_lights
          state: "on"
        then:
          # Если включен - выключаем все
          - service: light.turn_off
            target:
              entity_id: group.bathroom_all_lights
        else:
          # Иначе включаем все светильники
          - service: light.turn_on
            target:
              entity_id: light.bathroom_relay_l2
          - service: light.turn_on
            target:
              entity_id: group.bathroom_spots
            data:
              brightness_pct: 100
          - service: timer.start
            target:
              entity_id: timer.timer_bathroom

  bathroom_turn_on_night_mode:
    alias: "Включение ночного освещения в ванной"
    sequence:
      - service: light.turn_on
        target:
          entity_id: light.bathroom_spot_l1_philips
        data:
          brightness_pct: 10

  bathroom_turn_on_day_mode:
    alias: "Включение дневного освещения в ванной"
    sequence:
      - service: light.turn_on
        target:
          entity_id: light.bathroom_relay_l2
      - service: light.turn_on
        target:
          entity_id: group.bathroom_spots
        data:
          brightness_pct: 100

##############################################################################
#                              АВТОМАТИЗАЦИИ
##############################################################################
automation:
  # ----------------------------------------------------------------------------
  # Управление освещением: ручное переключение и запуск таймера
  # ----------------------------------------------------------------------------
  - id: "5525cbdc-3a8d-4464-908e-795c8205b40c"
    alias: "Ванная: Освещение, вкл/выкл с выключателя"
    description: "Автоматизация для управления светом в ванной через MQTT-выключатель."
    triggers:
      - platform: device
        domain: mqtt
        device_id: cc6ef89720abb376a24e910e13f37902
        type: action
        subtype: single_left
    actions:
      - if:
          condition: state
          entity_id: binary_sensor.is_night_mode
          state: "on"
        then:
          - service: script.turn_on
            target:
              entity_id: script.bathroom_toggle_night_mode
        else:
          - service: script.turn_on
            target:
              entity_id: script.bathroom_toggle_day_mode

  # ----------------------------------------------------------------------------
  # Включение света по движению/открытию двери (с учетом времени суток)
  # ----------------------------------------------------------------------------
  - id: "0007279c-13b5-402b-9aef-bf264273fa90"
    alias: "Ванная: Освещение, вкл по движению и датчикам открытия"
    description: "При срабатывании датчиков движения или открытии дверей в ванной, включается свет в зависимости от времени суток."
    triggers:
      - platform: state
        entity_id: binary_sensor.bathroom_open_door
        to: "on"
      - platform: state
        entity_id: binary_sensor.bathroom_motions
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"
    actions:
      - if:
          condition: state
          entity_id: binary_sensor.is_night_mode
          state: "on"
        then:
          - service: script.turn_on
            target:
              entity_id: script.bathroom_turn_on_night_mode
        else:
          - service: script.turn_on
            target:
              entity_id: script.bathroom_turn_on_day_mode

  # ----------------------------------------------------------------------------
  # Отмена таймера при обнаружении движения
  # ----------------------------------------------------------------------------
  - id: "50323f55-c6dd-483a-8799-af3c57e3e363"
    alias: "Ванная: Отмена таймера при обнаружении движения"
    description: "Если в ванной вновь обнаруживается движение во время работы таймера, таймер отменяется."
    triggers:
      - platform: state
        entity_id: binary_sensor.bathroom_motions
        to: "on"
    conditions:
      - condition: state
        entity_id: timer.timer_bathroom
        state: "active"
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"
    actions:
      - service: timer.cancel
        target:
          entity_id: timer.timer_bathroom

  # ----------------------------------------------------------------------------
  # Запуск таймера при отсутствии движения (1 минута)
  # ----------------------------------------------------------------------------
  - id: "e519fa4c-bbad-4b0d-b06c-8521b3b10131"
    alias: "Ванная: Запуск таймера при отсутствии движения"
    description: "Если движение в ванной отсутствует в течение 1 минуты, запускается таймер для автоматического выключения света."
    triggers:
      - platform: state
        entity_id: binary_sensor.bathroom_motions
        to: "off"
        for:
          minutes: 1
    conditions:
      - condition: state
        entity_id: group.bathroom_all_lights
        state: "on"
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"
    actions:
      - service: timer.start
        target:
          entity_id: timer.timer_bathroom

  # ----------------------------------------------------------------------------
  # Выключение света по истечении таймера отсутствия движения
  # ----------------------------------------------------------------------------
  - id: "b30b7ad8-6563-4279-a78f-1a113f9cb252"
    alias: "Ванная: Освещение, выключение по таймеру"
    description: "Эта автоматизация автоматически выключает свет в ванной по истечении таймера."
    triggers:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_bathroom
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"
    actions:
      - service: light.turn_off
        target:
          entity_id: group.bathroom_all_lights

  # ------------------------------------------------------------------------
  # Включение реле основного света при недоступности спотов
  # ------------------------------------------------------------------------
  - id: "0c5020c3-e674-4789-8086-38dbc07253d7"
    alias: "Ванная: Включение реле основного света при недоступности спотов"
    description: "Включает реле основного света (light.bathroom_main), если один или несколько спотов недоступны."
    triggers:
      - platform: state
        entity_id:
          - light.bathroom_spot_r1_philips
          - light.bathroom_spot_r2_philips
          - light.bathroom_spot_l1_philips
          - light.bathroom_spot_c1_philips
          - light.bathroom_spot_c2_philips
        to: "unavailable"
    conditions:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: light.bathroom_main
        state: "off"
    actions:
      - service: light.turn_on
        target:
          entity_id: light.bathroom_main
    mode: single
