automation:
  # Эта автоматизация предназначена для экономии энергии и продления срока службы батареи телефона.
  # Она отключает розетку, к которой подключен Google Pixel 8 PRO, если телефон полностью заряжен
  # (уровень заряда батареи достигает 99% или выше).
  # Это действие выполняется только ночью, в определенный временной промежуток с 01:00 до 07:00
  # утра по будням (с понедельника по пятницу).
  # Автоматизация помогает избежать перезарядки и потенциального перегрева устройства, что
  # особенно важно в ночные часы.

  - id: "1711479406635"
    alias: "Спальня: Отключение розетки при зарядке Google Pixel 8 PRO ночью"
    description: >
      Эта автоматизация предназначена для экономии энергии и продления срока службы батареи телефона.
      Она отключает розетку, к которой подключен Google Pixel 8 PRO, если телефон полностью заряжен (уровень заряда батареи достигает 99% или выше).
      Это действие выполняется только ночью, в определенный временной промежуток с 01:00 до 07:00 утра по будням (с понедельника по пятницу).
      Автоматизация помогает избежать перезарядки и потенциального перегрева устройства, что особенно важно в ночные часы.
    trigger:
      - type: battery_level
        platform: device
        device_id: 5846993890d4e0d41bca92b05a80991b
        entity_id: db12561215e9de9b577627c6ddbebc9a
        domain: sensor
        above: 99
    condition:
      - type: is_plugged_in
        condition: device
        device_id: 5846993890d4e0d41bca92b05a80991b
        entity_id: 1fdd31a1bb5e8df71a6a505122db2941
        domain: binary_sensor
      - condition: time
        after: "01:00:00"
        before: "07:00:00"
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - type: turn_off
        device_id: a0b08f4529f06331e4f52d16b8669d38
        entity_id: 557883b9510e1eb8a7f6d9de72e3c50b
        domain: switch
    mode: single
