################################################################################
# /packages/room_livingroom_humidifier.yaml
################################################################################
#
# АВТОМАТИЧЕСКОЕ УПРАВЛЕНИЕ УВЛАЖНИТЕЛЕМ В ГОСТИНОЙ
#
# ЛОГИКА:
# • Источник данных: sensor.livingroom_average_humidity
# • Включение: RH < 45% стабильно 3 мин
# • Выключение: RH > 50% стабильно 3 мин
# • Гистерезис: работающий остаётся ON, пока RH < 50%
# • Антидребезг: мин. время работы/простоя (10/15 мин)
#
# УСТРОЙСТВО:
# • humidifier.xiaomi_cn_823407205_p3
#
# ЗАВИСИМОСТИ:
# • helper_climate_common.yaml — таймеры, скрипт обновления
# • room_livingroom.yaml — усреднённая влажность
#
################################################################################

##############################################################################
#                           ВХОДНЫЕ ПЕРЕМЕННЫЕ
##############################################################################

input_boolean:
  # --------------------------------------------------------------------------
  # Автоматический режим увлажнителя
  # --------------------------------------------------------------------------
  # Мастер-переключатель автоматизации увлажнителя.
  # OFF → увлажнитель управляется только вручную
  # ON → автоматическое управление на основе влажности
  livingroom_humidifier_auto:
    name: "Гостиная: авто-режим увлажнителя"
    icon: mdi:autorenew
    initial: true

input_number:
  # --------------------------------------------------------------------------
  # Нижний порог влажности (%)
  # --------------------------------------------------------------------------
  # Мягкий порог для гистерезиса.
  # Увлажнитель включается, когда RH < этого значения стабильно 3 мин.
  # Работающий увлажнитель остаётся ON, пока RH < верхнего порога.
  livingroom_hum_low:
    name: "Гостиная: нижний порог RH (%)"
    min: 20
    max: 60
    step: 1
    initial: 45
    unit_of_measurement: "%"

  # --------------------------------------------------------------------------
  # Верхний порог влажности (%)
  # --------------------------------------------------------------------------
  # Жёсткий порог для выключения.
  # Увлажнитель выключается, когда RH > этого значения стабильно 3 мин.
  livingroom_hum_high:
    name: "Гостиная: верхний порог RH (%)"
    min: 30
    max: 70
    step: 1
    initial: 50
    unit_of_measurement: "%"

  # --------------------------------------------------------------------------
  # Минимальное время работы (мин)
  # --------------------------------------------------------------------------
  # Антидребезг: увлажнитель не выключится раньше этого времени.
  # Предотвращает частые включения/выключения при колебаниях влажности.
  # Гарантирует эффективное увлажнение помещения.
  livingroom_hum_min_on_min:
    name: "Мин. время работы увлажнителя (мин)"
    min: 1
    max: 60
    step: 1
    initial: 10

  # --------------------------------------------------------------------------
  # Минимальное время простоя (мин)
  # --------------------------------------------------------------------------
  # Антидребезг: увлажнитель не включится раньше этого времени.
  # Предотвращает износ устройства от частых запусков.
  # Позволяет влаге равномерно распределиться по помещению.
  livingroom_hum_min_off_min:
    name: "Мин. время простоя увлажнителя (мин)"
    min: 1
    max: 60
    step: 1
    initial: 15

##############################################################################
#                               БИНАРНЫЕ СЕНСОРЫ
##############################################################################

binary_sensor:
  - platform: template
    sensors:
      # ------------------------------------------------------------------------
      # Необходимость увлажнения (гистерезис)
      # ------------------------------------------------------------------------
      # Вычисляет, нужно ли включить/выключить увлажнитель.
      #
      # ЛОГИКА ГИСТЕРЕЗИСА:
      # • Выключен → включается при RH < 45%
      # • Включён → остаётся ON, пока RH < 50%
      # • Включён → выключается при RH ≥ 50%
      #
      # ИСТОЧНИК ДАННЫХ:
      # • sensor.livingroom_average_humidity (усреднённая влажность из helper_climate_common)
      # • Вычисляется как среднее между двумя датчиками
      #
      # ЗАЩИТА ОТ ОШИБОК:
      # • Если датчик недоступен → сохраняет предыдущее состояние
      # • Валидация порогов: high всегда > low
      #
      # ИКОНКА:
      # • ON → mdi:water-alert (требуется увлажнение)
      # • OFF → mdi:water-check (влажность в норме)
      livingroom_need_humidify:
        unique_id: livingroom_need_humidify
        friendly_name: "Гостиная: нужна влажность (гистерезис)"
        device_class: moisture
        icon_template: >-
          {% if is_state('binary_sensor.livingroom_need_humidify', 'on') %}
            mdi:water-alert
          {% else %}
            mdi:water-check
          {% endif %}

        availability_template: >-
          {{ states('sensor.livingroom_average_humidity') not in ['unknown','unavailable',''] }}

        value_template: >-
          {% set rh = states('sensor.livingroom_average_humidity') | float(default=none) %}
          {% if rh is none %}
            {{ states('binary_sensor.livingroom_need_humidify') }}
          {% else %}
            {% set low  = states('input_number.livingroom_hum_low')  | float(45) %}
            {% set high = states('input_number.livingroom_hum_high') | float(50) %}
            {% if low >= high %}{% set high = low + 1 %}{% endif %}
            {% set was_on = is_state('binary_sensor.livingroom_need_humidify','on') %}
            {% if was_on %}
              {{ rh < high }}
            {% else %}
              {{ rh < low }}
            {% endif %}
          {% endif %}

##############################################################################
#                              АВТОМАТИЗАЦИИ
##############################################################################

automation:
  # ==========================================================================
  # АВТОМАТИЧЕСКОЕ УПРАВЛЕНИЕ УВЛАЖНИТЕЛЕМ
  # ==========================================================================

  # --------------------------------------------------------------------------
  # Включение увлажнителя при низкой влажности
  # --------------------------------------------------------------------------
  - id: "95170174-7e11-4acc-9dae-b575eaede9c8"
    alias: "Гостиная: включить увлажнитель"
    description: >
      Включает увлажнитель при снижении влажности ниже порога.

      ТРИГГЕР:
      • binary_sensor.livingroom_need_humidify: OFF → ON стабильно 3 мин
      • RH < 45% (нижний порог)

      УСЛОВИЯ:
      1. Автоматический режим включён (livingroom_humidifier_auto = ON)
      2. Минимальное время простоя прошло (≥15 мин с последнего выключения)

      ЗАЩИТА ОТ ЧАСТЫХ ВКЛЮЧЕНИЙ:
      • Триггер с задержкой 3 мин → защита от кратковременных просадок
      • Проверка времени простоя → защита от износа устройства
      • Позволяет влаге равномерно распределиться

      ДЕЙСТВИЕ:
      • Включает humidifier.xiaomi_cn_823407205_p3
      • Обновляет input_datetime.humidifier_last_on (через helper_climate_common)

      ВЗАИМОДЕЙСТВИЕ С ДРУГИМИ АВТОМАТИЗАЦИЯМИ:
      • При открытии балконных дверей → выключится (helper_climate_common)
      • При закрытии дверей → восстановится, если был включён
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_need_humidify
        from: "off"
        to: "on"
        for:
          minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.livingroom_humidifier_auto
        state: "on"
      - condition: template
        value_template: >-
          {% set last_off = states('input_datetime.humidifier_last_off') %}
          {% if last_off in ['unknown','unavailable'] %}
            true
          {% else %}
            {% set minutes_off = (as_timestamp(now()) - as_timestamp(last_off)) / 60 %}
            {{ minutes_off >= states('input_number.livingroom_hum_min_off_min') | int }}
          {% endif %}
    action:
      - service: humidifier.turn_on
        target:
          entity_id: humidifier.xiaomi_cn_823407205_p3

  # --------------------------------------------------------------------------
  # Выключение увлажнителя при достижении целевой влажности
  # --------------------------------------------------------------------------
  - id: "feb01173-2f87-4aec-8bba-877b685d4bf2"
    alias: "Гостиная: выключить увлажнитель"
    description: >
      Выключает увлажнитель при достижении целевой влажности.

      ТРИГГЕР:
      • binary_sensor.livingroom_need_humidify: ON → OFF стабильно 3 мин
      • RH ≥ 50% (верхний порог)

      УСЛОВИЯ:
      1. Автоматический режим включён (livingroom_humidifier_auto = ON)
      2. Минимальное время работы прошло (≥10 мин с последнего включения)

      ЗАЩИТА ОТ ЧАСТЫХ ВЫКЛЮЧЕНИЙ:
      • Триггер с задержкой 3 мин → защита от кратковременных всплесков
      • Проверка времени работы → гарантия эффективного увлажнения

      ГИСТЕРЕЗИС:
      • Включается при RH < 45%
      • Выключается при RH ≥ 50%
      • Зона стабильности: 45–50%

      ДЕЙСТВИЕ:
      • Выключает humidifier.xiaomi_cn_823407205_p3
      • Обновляет input_datetime.humidifier_last_off (через helper_climate_common)

      ВЗАИМОДЕЙСТВИЕ С ДРУГИМИ АВТОМАТИЗАЦИЯМИ:
      • Сохраняет состояние при shutdown HA (helper_climate_common)
      • Восстанавливает состояние при старте HA
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_need_humidify
        from: "on"
        to: "off"
        for:
          minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.livingroom_humidifier_auto
        state: "on"
      - condition: template
        value_template: >-
          {% set last_on = states('input_datetime.humidifier_last_on') %}
          {% if last_on in ['unknown','unavailable'] %}
            true
          {% else %}
            {% set minutes_on = (as_timestamp(now()) - as_timestamp(last_on)) / 60 %}
            {{ minutes_on >= states('input_number.livingroom_hum_min_on_min') | int }}
          {% endif %}
    action:
      - service: humidifier.turn_off
        target:
          entity_id: humidifier.xiaomi_cn_823407205_p3

  # ==========================================================================
  # ТЕХНИЧЕСКИЕ ТРИГГЕРЫ ДЛЯ УВЕДОМЛЕНИЙ
  # ==========================================================================

  # --------------------------------------------------------------------------
  # Триггер: фильтр увлажнителя <10%
  # --------------------------------------------------------------------------
  - id: "a6f8e632-52ec-4857-a6f3-b9b74a69e1a5"
    alias: "Триггер: фильтр увлажнителя <10%"
    description: >
      Технический триггер для уведомлений о необходимости замены фильтра.

      ТРИГГЕР:
      • sensor.xiaomi_cn_823407205_p3_filter_life_level_p_8_1 < 10% стабильно 1 мин

      НАЗНАЧЕНИЕ:
      • Активирует сенсор в других пакетах (например, notifications.yaml)
      • Не выполняет действий напрямую (actions: [])

      ИСПОЛЬЗОВАНИЕ:
      • Другая автоматизация отслеживает изменение last_triggered
      • Отправляет уведомление через Telegram/TTS
      • Устанавливает флаг humidifier_filter_replace_notified

      ВАЖНО:
      • Фильтр увлажнителя требует замены при износе >90%
      • Изношенный фильтр снижает эффективность увлажнения
      • Может привести к размножению бактерий
    triggers:
      - trigger: numeric_state
        entity_id: sensor.xiaomi_cn_823407205_p3_filter_life_level_p_8_1
        below: 10
        for: "00:01:00"
    actions: []

  # --------------------------------------------------------------------------
  # Триггер: фильтр увлажнителя >10%
  # --------------------------------------------------------------------------
  - id: "121ce3ac-de14-4ba8-984d-454c7ae9b3ec"
    alias: "Триггер: фильтр увлажнителя >10%"
    description: >
      Технический триггер для сброса уведомлений о замене фильтра.

      ТРИГГЕР:
      • sensor.xiaomi_cn_823407205_p3_filter_life_level_p_8_1 > 10% стабильно 1 мин

      НАЗНАЧЕНИЕ:
      • Сбрасывает флаг humidifier_filter_replace_notified
      • Позволяет повторно уведомить при следующем износе

      ИСПОЛЬЗОВАНИЕ:
      • После замены фильтра уровень > 10% → триггер сбрасывает уведомление
      • При следующем износе < 10% → уведомление снова отправляется

      ЛОГИКА:
      1. Фильтр новый (100%) → уведомление не требуется
      2. Фильтр изнашивается до 10% → срабатывает триггер "< 10%" → уведомление
      3. Фильтр заменён (100%) → срабатывает триггер "> 10%" → сброс флага
      4. Цикл повторяется
    triggers:
      - trigger: numeric_state
        entity_id: sensor.xiaomi_cn_823407205_p3_filter_life_level_p_8_1
        above: 10
        for: "00:01:00"
    actions: []

  # --------------------------------------------------------------------------
  # Триггер: низкий уровень воды в увлажнителе
  # --------------------------------------------------------------------------
  - id: "0889817f-ac88-4d48-8cbd-a0f57efa6f04"
    alias: "Триггер: низкий уровень воды в увлажнителе"
    description: >
      Технический триггер для уведомлений о необходимости долить воду.

      ТРИГГЕР:
      • event.xiaomi_cn_823407205_p3_low_water_level_e_2_1 срабатывает
      • Увлажнитель обнаруживает низкий уровень воды в резервуаре

      НАЗНАЧЕНИЕ:
      • Активирует уведомление в других пакетах
      • Не выполняет действий напрямую (actions: [])

      ИСПОЛЬЗОВАНИЕ:
      • Другая автоматизация отслеживает событие
      • Отправляет уведомление через Telegram/TTS
      • Устанавливает флаг humidifier_low_water_notified

      ВАЖНО:
      • Увлажнитель автоматически выключается при низком уровне воды
      • Работа без воды может повредить устройство
      • Рекомендуется долить воду в течение 1-2 часов

      АВТОМАТИЧЕСКИЙ СБРОС:
      • Когда вода доливается → устройство продолжает работу
      • Флаг humidifier_low_water_notified сбрасывается автоматически
    triggers:
      - trigger: state
        entity_id: event.xiaomi_cn_823407205_p3_low_water_level_e_2_1
    actions: []
