################################################################################
# /packages/room_kitchen.yaml
################################################################################
#
# Пакет Home Assistant для управления освещением и климатом (в частности, вытяжкой)
# на кухне. Основная функциональность:
#  • Переключение освещения через два разных выключателя (правой клавишей
#    кухонного выключателя и сценическим выключателем).
#  • Контроль «перегрева» и «повышенной влажности» на кухне с помощью
#    сравнения температуры/влажности с гостиной и отправка голосового
#    уведомления (script.yandex_tts_kitchen_fan_alert) при необходимости
#    включить вытяжку. Также ведётся флаг input_boolean.kitchen_fan_cool_down,
#    препятствующий повторным уведомлениям.
#
################################################################################

binary_sensor:
  - platform: template
    sensors:
      kitchen_need_ventilation:
        unique_id: kitchen_need_ventilation
        friendly_name: "Кухня: Нужна вытяжка (с гистерезисом)"
        device_class: problem
        availability_template: >
          {{ states('sensor.kitchen_th_temperature') not in ['unknown','unavailable',''] and
             states('sensor.livingroom_climat_sensor_temperature') not in ['unknown','unavailable',''] and
             states('sensor.kitchen_th_humidity') not in ['unknown','unavailable',''] and
             states('sensor.livingroom_climat_sensor_humidity') not in ['unknown','unavailable',''] }}
        value_template: >
          {% set temp_kitchen = states('sensor.kitchen_th_temperature') | float(0) %}
          {% set temp_living = states('sensor.livingroom_climat_sensor_temperature') | float(0) %}
          {% set hum_kitchen  = states('sensor.kitchen_th_humidity') | float(0) %}
          {% set hum_living   = states('sensor.livingroom_climat_sensor_humidity') | float(0) %}

          {% set temp_diff = temp_kitchen - temp_living %}
          {% set hum_diff  = hum_kitchen  - hum_living  %}

          {% set temp_high = states('input_number.kitchen_temp_hysteresis_threshold_high') | float(0) %}
          {% set temp_low  = states('input_number.kitchen_temp_hysteresis_threshold_low')  | float(0) %}
          {% set hum_high  = states('input_number.kitchen_hum_hysteresis_threshold_high')  | float(0) %}
          {% set hum_low   = states('input_number.kitchen_hum_hysteresis_threshold_low')   | float(0) %}

          {% set was_on = is_state('binary_sensor.kitchen_need_ventilation','on') %}
          {% if was_on %}
            {{ temp_diff > temp_low or hum_diff > hum_low }}
          {% else %}
            {{ temp_diff > temp_high or hum_diff > hum_high }}
          {% endif %}

input_boolean:
  # Флаг для предотвращения повторных уведомлений о необходимости включить вытяжку
  kitchen_fan_cool_down:
    name: "Kitchen Fan Cool Down"
    initial: off
    icon: mdi:fan-alert

input_number:
  kitchen_temp_hysteresis_threshold_high:
    name: "Жёсткий порог температуры (°C)"
    min: 1
    max: 10
    step: 0.5
    initial: 5
  kitchen_temp_hysteresis_threshold_low:
    name: "Мягкий порог температуры (°C)"
    min: 1
    max: 10
    step: 0.5
    initial: 3
  kitchen_hum_hysteresis_threshold_high:
    name: "Жёсткий порог влажности (%)"
    min: 5
    max: 20
    step: 1
    initial: 10
  kitchen_hum_hysteresis_threshold_low:
    name: "Мягкий порог влажности (%)"
    min: 5
    max: 20
    step: 1
    initial: 8

  # Новые настраиваемые интервалы
  kitchen_notification_cooldown_min:
    name: "Кухня: Интервал между уведомлениями (мин)"
    min: 5
    max: 120
    step: 5
    initial: 30
  kitchen_fan_delay_min:
    name: "Кухня: Задержка выключения вытяжки (мин)"
    min: 0.5
    max: 10
    step: 0.5
    initial: 1

timer:
  # Таймер для предотвращения повторных уведомлений
  kitchen_notification_cooldown_timer:
    duration: "00:30:00" # Базовое; фактическая длительность задаётся при старте

  # Таймер для задержки выключения вытяжки
  kitchen_fan_delay_timer:
    duration: "00:01:00" # Базовое; фактическая длительность задаётся при старте

automation:
  ##########################################################################
  # ПЕРЕКЛЮЧЕНИЕ ОСВЕЩЕНИЯ ЧЕРЕЗ ВЫКЛЮЧАТЕЛИ
  ##########################################################################
  - id: "b29835d5-9911-47ec-8630-2adda70be854"
    alias: "Кухня: Переключение освещения выключателями"
    description: >
      Управление основным светом и подсветкой фартука через кухонный выключатель
      (правая клавиша) и сценический выключатель (1_single / 2_single).
    mode: restart
    trigger:
      - platform: device
        domain: mqtt
        device_id: cc6ef89720abb376a24e910e13f37902
        type: action
        subtype: single_right
        id: kitchen_switch_right
      - platform: device
        domain: mqtt
        device_id: 719cda594198c3eafa3817b9230f2afa
        type: action
        subtype: 1_single
        id: scenic_1_single
      - platform: device
        domain: mqtt
        device_id: 719cda594198c3eafa3817b9230f2afa
        type: action
        subtype: 2_single
        id: scenic_2_single
    condition:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: kitchen_switch_right
            sequence:
              - type: toggle
                device_id: cc6ef89720abb376a24e910e13f37902
                entity_id: 6ecc35aae49d8307be87809073a32233
                domain: light
          - conditions:
              - condition: trigger
                id: scenic_1_single
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.kitchen_fartuh
          - conditions:
              - condition: trigger
                id: scenic_2_single
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.kitchen_main_light

  ##########################################################################
  # ПРЕДУПРЕЖДЕНИЕ О НЕОБХОДИМОСТИ ВКЛЮЧЕНИЯ ВЫТЯЖКИ
  ##########################################################################
  - id: "dc8af8f7-c0f5-4244-867b-00fc546039ba"
    alias: "Кухня: Предупреждение о необходимости включения вытяжки (гистерезис)"
    description: >
      При включении binary_sensor.kitchen_need_ventilation (off→on) отправляем уведомление
      и выставляем флаг kitchen_fan_cool_down, чтобы не повторяться.
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_need_ventilation
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.kitchen_fan_cool_down
        state: "off"
      - condition: state
        entity_id: timer.kitchen_notification_cooldown_timer
        state: "idle"
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"
    action:
      - service: script.yandex_tts_kitchen_fan_alert
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.kitchen_fan_cool_down
      - service: timer.start
        target:
          entity_id: timer.kitchen_notification_cooldown_timer
        data:
          duration: "{{ (states('input_number.kitchen_notification_cooldown_min') | float(30) * 60) | int }}"

  ##########################################################################
  # СБРОС ПРЕДУПРЕЖДЕНИЯ О ВЫТЯЖКЕ ПРИ НОРМАЛИЗАЦИИ
  ##########################################################################
  - id: "8b7c3a73-7d74-4e6f-b1d5-4a9c1e3a9c12"
    alias: "Кухня: Сброс предупреждения о необходимости вытяжки (гистерезис)"
    description: "Когда условия нормализовались (off), сбрасываем флаг."
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_need_ventilation
        from: "on"
        to: "off"
    condition: []
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.kitchen_fan_cool_down

  ##########################################################################
  # СБРОС ФЛАГА ВЫТЯЖКИ ПРИ СТАРТЕ
  ##########################################################################
  - id: "10f4f44c-a559-4281-9a1b-18aac1fd845b"
    alias: "Кухня: Сброс флага вытяжки при старте"
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.kitchen_need_ventilation
        state: "off"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.kitchen_fan_cool_down

  ##########################################################################
  # АВТОМАТИЧЕСКОЕ ВКЛЮЧЕНИЕ ВЫТЯЖКИ
  ##########################################################################
  - id: "e2d5d614-46cf-4706-9bfe-7a17cd81f0c1"
    alias: "Кухня: Автоматическое включение вытяжки"
    description: "Включает вытяжку, когда need_ventilation устойчиво on 1 минуту."
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_need_ventilation
        from: "off"
        to: "on"
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: switch.sonoff_10024c81be
        state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.sonoff_10024c81be

  ##########################################################################
  # ЗАПУСК ТАЙМЕРА ЗАДЕРЖКИ ВЫКЛЮЧЕНИЯ ВЫТЯЖКИ
  ##########################################################################
  - id: "d2986069-fb9c-4425-afc7-1b17f96cfff3"
    alias: "Кухня: Запуск таймера задержки выключения вытяжки"
    description: "Стартует таймер, когда условия нормализовались."
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_need_ventilation
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: switch.sonoff_10024c81be
        state: "on"
    action:
      - service: timer.start
        target:
          entity_id: timer.kitchen_fan_delay_timer
        data:
          duration: "{{ (states('input_number.kitchen_fan_delay_min') | float(1) * 60) | int }}"

  ##########################################################################
  # ВЫКЛЮЧЕНИЕ ВЫТЯЖКИ ПО ТАЙМЕРУ
  ##########################################################################
  - id: "95fecbf7-3ac8-4b4a-a7a8-a857a307be68"
    alias: "Кухня: Выключение вытяжки по таймеру"
    description: "Выключает вытяжку по окончании таймера, если условия нормальны."
    mode: single
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.kitchen_fan_delay_timer
    condition:
      - condition: state
        entity_id: binary_sensor.kitchen_need_ventilation
        state: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.sonoff_10024c81be
