# /packages/bathroom_lights.yaml
#############################
# Пакет конфигураций для ванной комнаты (bathroom_lights).
# В этом файле описаны настройки освещения в ванной, а также
# автоматизации, позволяющие управлять яркостью и цветовой температурой
# в ночное и утреннее время.
#
#############################

##############################################################################
#                                  ОСВЕЩЕНИЕ
##############################################################################
light:
  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_r1_philips
    host: !secret bathroom_spot_r1_ip
    token: !secret bathroom_spot_r1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_r2_philips
    host: !secret bathroom_spot_r2_ip
    token: !secret bathroom_spot_r2_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_l1_philips
    host: !secret bathroom_spot_l1_ip
    token: !secret bathroom_spot_l1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_c1_philips
    host: !secret bathroom_spot_c1_ip
    token: !secret bathroom_spot_c1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_c2_philips
    host: !secret bathroom_spot_c2_ip
    token: !secret bathroom_spot_c2_token
    model: philips.light.downlight

##############################################################################
#                                   ГРУППЫ
##############################################################################
group:
  bathroom_lights_group:
    name: Bathroom Lights
    entities:
      - light.bathroom_spot_r1_philips
      - light.bathroom_spot_r2_philips
      - light.bathroom_spot_l1_philips
      - light.bathroom_spot_c1_philips
      - light.bathroom_spot_c2_philips

##############################################################################
#                             АВТОМАТИЗАЦИИ
##############################################################################
automation:
  # ------------------------------------------------------------------------
  # УСТАНОВКА МИНИМАЛЬНОЙ ЯРКОСТИ ДЛЯ СВЕТА В ВАННОЙ НОЧЬЮ
  # ------------------------------------------------------------------------
  # Данная автоматизация срабатывает, когда любой из спотов в ванной
  # включается между полуночью и 06:00 утра. Свет автоматически
  # устанавливается на 10% яркости и более тёплую цветовую температуру (333),
  # чтобы не слепить глаза и создать мягкое освещение в ночные часы.
  #
  # Применяется к:
  #   - light.bathroom_spot_r1_philips
  #   - light.bathroom_spot_r2_philips
  #   - light.bathroom_spot_l1_philips
  #   - light.bathroom_spot_c1_philips
  #   - light.bathroom_spot_c2_philips
  # ------------------------------------------------------------------------
  - id: "5751bda3-f9c2-4173-808e-c44b12519960"
    alias: "Ванная: Снижение яркости и температуры освещения"
    mode: queued
    trigger:
      - platform: state
        entity_id:
          - light.bathroom_spot_r1_philips
          - light.bathroom_spot_r2_philips
          - light.bathroom_spot_l1_philips
          - light.bathroom_spot_c1_philips
          - light.bathroom_spot_c2_philips
        to: "on"
    condition:
      - condition: time
        after: "00:00:00"
        before: "06:00:00"
    action:
      - service: light.turn_on
        data:
          brightness_pct: 10
          # color_temp: 333
          color_temp_kelvin: 3000 # Заменено с mireds (333) на кельвины (~3000K)
        target:
          entity_id: "{{ trigger.entity_id }}"

  # ------------------------------------------------------------------------
  # ВОССТАНОВЛЕНИЕ ПОЛНОЙ ЯРКОСТИ СВЕТА УТРОМ
  # ------------------------------------------------------------------------
  # Эта автоматизация срабатывает в 06:00 утра, чтобы вернуть освещение
  # в ванной к полному уровню яркости (100%) и более холодной цветовой
  # температуре (175).
  # ------------------------------------------------------------------------

  - id: "20ce33b4-0084-450a-aa8c-3faa6db984c7"
    alias: "Ванная: Восстановление яркости и температуры освещения"
    mode: queued
    trigger:
      - platform: state
        entity_id:
          - light.bathroom_spot_r1_philips
          - light.bathroom_spot_r2_philips
          - light.bathroom_spot_l1_philips
          - light.bathroom_spot_c1_philips
          - light.bathroom_spot_c2_philips
        to: "on"
    condition:
      - condition: time
        after: "06:00:00"
        before: "23:59:00"
    action:
      - service: light.turn_on
        target:
          entity_id: "{{ trigger.entity_id }}"
        data:
          brightness_pct: 100
          # color_temp: 175
          color_temp_kelvin: 5700 # Заменено с mireds (175) на кельвины (~5700K)

  - id: "0c5020c3-e674-4789-8086-38dbc07253d7"
    alias: "Ванная: Включение реле основного света при недоступности спотов"
    description: "Включает реле основной свет, если хотя бы один из спотов недоступен и не фаза загрузки."
    trigger:
      - platform: state
        entity_id:
          - light.bathroom_spot_r1_philips
          - light.bathroom_spot_r2_philips
          - light.bathroom_spot_l1_philips
          - light.bathroom_spot_c1_philips
          - light.bathroom_spot_c2_philips
        to: "unavailable"

    condition:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: light.bathroom_main
        state: "off"

    action:
      - service: light.turn_on
        target:
          entity_id: light.bathroom_main

    mode: single
