################################################################################
# /packages/room_bedroom.yaml
################################################################################
#
# УПРАВЛЕНИЕ СПАЛЬНЕЙ: ЭНЕРГОСБЕРЕЖЕНИЕ + КОНТРОЛЬ ТЕМПЕРАТУРЫ
#
# ФУНКЦИИ:
# 1. Энергосбережение при зарядке устройств
#    • Автоотключение розетки зарядки при полной батарее (ночью)
#    • Защита батареи от перезаряда
#    • Экономия электроэнергии
#
# 2. Контроль микроклимата
#    • Мониторинг температуры (сглаженное значение)
#    • Уведомления о низкой температуре при открытом окне/балконе
#    • Антиспам уведомлений (таймер 20 минут)
#    • Голосовые уведомления через Яндекс.Станцию
#
# УСТРОЙСТВА:
# • sensor.bedroom_th_sensor_temperature — датчик температуры спальни
# • sensor.pixel_8_pro_battery_level — уровень заряда телефона
# • sensor.pixel_8_pro_battery_state — состояние зарядки телефона
# • switch.0x00158d0002530ba3 — розетка зарядки телефона
# • binary_sensor.0x00158d00044d5d11_contact — датчик открытия балкона/окна
#
# ЗАВИСИМОСТИ:
# • script.yandex_tts_temp_status — голосовое уведомление о температуре
# • person.master — статус присутствия владельца
# • binary_sensor.someone_is_home_2 — наличие людей дома
#
# ЛОГИКА ЭНЕРГОСБЕРЕЖЕНИЯ:
# ┌──────────────────────────────────────────────────────────────────┐
# │ Зарядка ночью (01:00 - 07:00)                                    │
# │ ↓                                                                │
# │ Батарея ≥ 99% (устойчиво 1 минуту)                              │
# │ ↓                                                                │
# │ Отключение розетки зарядки                                       │
# │ ↓                                                                │
# │ Защита батареи от перезаряда                                     │
# └──────────────────────────────────────────────────────────────────┘
#
# ЛОГИКА КОНТРОЛЯ ТЕМПЕРАТУРЫ:
# ┌──────────────────────────────────────────────────────────────────┐
# │ Температура < 20°C (устойчиво 1 минуту)                          │
# │ ↓                                                                │
# │ Балкон/окно открыто                                              │
# │ ↓                                                                │
# │ Уведомление (Telegram + голос)                                   │
# │ ↓                                                                │
# │ Флаг антиспама = ON                                              │
# │ ↓                                                                │
# │ Таймер 20 минут                                                  │
# │ ↓                                                                │
# │ Флаг антиспама = OFF (возможно новое уведомление)                │
# └──────────────────────────────────────────────────────────────────┘
#
################################################################################

##############################################################################
#                        НАСТРАИВАЕМЫЕ ПАРАМЕТРЫ
##############################################################################

input_number:
  # ==========================================================================
  # Период сброса уведомлений о температуре в спальне
  # ==========================================================================
  # НАЗНАЧЕНИЕ:
  # • Интервал между повторными уведомлениями о низкой температуре
  # • Защита от спама уведомлений
  #
  # ДЛИТЕЛЬНОСТЬ:
  # • По умолчанию: 20 минут
  # • Можно настроить от 10 до 60 минут
  # ==========================================================================
  bedroom_low_th_notification_reset_period:
    name: "Спальня: интервал уведомлений о температуре (мин)"
    min: 10
    max: 60
    step: 5
    initial: 20
    icon: mdi:timer-refresh

##############################################################################
#                          INPUT BOOLEAN
##############################################################################

input_boolean:
  # Флаг антиспама уведомлений о температуре
  bedroom_th_notice:
    name: "Спальня: уведомление о температуре отправлено"
    initial: false
    icon: mdi:bell-ring

##############################################################################
#                               ТАЙМЕРЫ
##############################################################################

timer:
  # ==========================================================================
  # Таймер сброса флага уведомлений о температуре
  # ==========================================================================
  # НАЗНАЧЕНИЕ:
  # • Автоматический сброс флага антиспама
  # • Разрешает отправку новых уведомлений после таймаута
  #
  # ДЛИТЕЛЬНОСТЬ:
  # • По умолчанию: 20 минут
  # • Задаётся динамически через input_number.bedroom_low_th_notification_reset_period
  # ==========================================================================
  bedroom_th_notice_reset:
    name: "Спальня: сброс флага уведомлений о температуре"
    duration: "00:20:00"
    icon: mdi:timer-refresh

##############################################################################
#                          СГЛАЖЕННЫЕ СЕНСОРЫ
##############################################################################

sensor:
  # ==========================================================================
  # Сглаженная температура спальни (2 мин скользящее среднее)
  # ==========================================================================
  # НАЗНАЧЕНИЕ:
  # • Устранение кратковременных скачков температуры
  # • Более стабильные показания для триггеров
  # • Защита от ложных срабатываний уведомлений
  #
  # ОКНО СГЛАЖИВАНИЯ:
  # • 2 минуты
  # • Достаточно для фильтрации шумов, но быстро реагирует на реальные изменения
  #
  # ТОЧНОСТЬ:
  # • 2 знака после запятой (0.01°C)
  # ==========================================================================
  - platform: filter
    name: "Температура в спальне (сглаженная)"
    unique_id: bedroom_temperatura_sglazhennaia
    entity_id: sensor.bedroom_th_sensor_temperature
    filters:
      - filter: time_simple_moving_average
        window_size: "00:02"
        precision: 2

##############################################################################
#                             АВТОМАТИЗАЦИИ
##############################################################################

automation:
  # ==========================================================================
  # ЭНЕРГОСБЕРЕЖЕНИЕ ПРИ ЗАРЯДКЕ УСТРОЙСТВ
  # ==========================================================================

  # --------------------------------------------------------------------------
  # Отключение розетки зарядки при полной батарее (ночью)
  # --------------------------------------------------------------------------
  - id: "a658b6fc-d264-4c6b-8185-e3b503f5a7e5"
    alias: "Спальня: отключение розетки зарядки при полной батарее (ночью)"
    description: >
      Автоматически отключает розетку зарядки, когда телефон заряжен почти полностью.

      ТРИГГЕР:
      • Уровень заряда ≥ 99% (устойчиво 1 минуту)

      УСЛОВИЯ (ВСЕ ДОЛЖНЫ БЫТЬ ВЫПОЛНЕНЫ):
      • Телефон заряжается (battery_state = charging)
      • Ночное время: 01:00 - 07:00
      • Фаза запуска завершена
      • Данные батареи доступны
      • Розетка включена (есть что отключать)

      ДЕЙСТВИЯ:
      • Отключение розетки зарядки
      • Запись в лог

      НАЗНАЧЕНИЕ:
      • Защита батареи от перезаряда (продление срока службы)
      • Экономия электроэнергии (нет паразитного потребления)
      • Снижение нагрева батареи ночью

      ВРЕМЕННОЕ ОКНО:
      • 01:00 - 07:00 — когда обычно спят
      • Днём не срабатывает (может понадобиться быстрая дозарядка)

      ЗАДЕРЖКА 1 МИНУТА:
      • Защита от кратковременных колебаний уровня заряда
      • Подтверждение полного заряда

      ПРИМЕРЫ:
      1. 03:00, заряд 99.5%, заряжается → розетка ВЫКЛ (защита батареи)
      2. 15:00, заряд 100%, заряжается → ничего не происходит (днём)
      3. 03:00, заряд 98%, заряжается → ничего не происходит (ещё не полный)

      ВОССТАНОВЛЕНИЕ:
      • При отключении телефона от зарядки утром можно снова вставить в розетку
      • Розетку можно включить вручную или автоматически по расписанию
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id: sensor.pixel_8_pro_battery_level
        above: 99
        for:
          minutes: 1

    conditions:
      - condition: state
        entity_id: sensor.pixel_8_pro_battery_state
        state: "charging"

      - condition: time
        after: "01:00:00"
        before: "07:00:00"

      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"

      - condition: template
        value_template: >-
          {{ states('sensor.pixel_8_pro_battery_level') not in ['unknown', 'unavailable', ''] }}

      - condition: state
        entity_id: switch.0x00158d0002530ba3
        state: "on"

    actions:
      - action: switch.turn_off
        target:
          entity_id: switch.0x00158d0002530ba3

  # ==========================================================================
  # КОНТРОЛЬ ТЕМПЕРАТУРЫ
  # ==========================================================================

  # --------------------------------------------------------------------------
  # Уведомление о низкой температуре при открытом окне/балконе
  # --------------------------------------------------------------------------
  - id: "9f1229c2-0ce2-4483-9953-1f6cdc6fa18e"
    alias: "Спальня: уведомление о низкой температуре (при открытом окне)"
    description: >
      Отправляет уведомление, когда температура опускается ниже 20°C при открытом балконе.

      ТРИГГЕР:
      • Сглаженная температура < 20°C (устойчиво 1 минуту)

      УСЛОВИЯ (ВСЕ ДОЛЖНЫ БЫТЬ ВЫПОЛНЕНЫ):
      • Фаза запуска завершена
      • Режим тишины выключен (не будит ночью)
      • Балкон/окно открыто (есть причина холода)
      • Кто-то дома (есть кому получить уведомление)
      • Датчик температуры доступен
      • Флаг антиспама выключен (не было уведомления недавно)

      ДЕЙСТВИЯ:
      1. Telegram-уведомление (если мастер дома)
      2. Голосовое уведомление (script.yandex_tts_temp_status)
      3. Установка флага антиспама = ON
      4. Запуск таймера сброса флага (20 мин)
      5. Запись в лог

      ЛОГИКА АНТИСПАМА:
      ┌────────────────────────────────────────┐
      │ Уведомление отправлено                 │
      │ ↓                                      │
      │ Флаг антиспама = ON                    │
      │ ↓                                      │
      │ Таймер 20 минут                        │
      │ ↓                                      │
      │ Флаг антиспама = OFF                   │
      │ ↓                                      │
      │ Возможно новое уведомление             │
      └────────────────────────────────────────┘

      СГЛАЖИВАНИЕ ТЕМПЕРАТУРЫ:
      • Скользящее среднее за 2 минуты
      • Защита от кратковременных скачков
      • Стабильные показания

      УСЛОВИЕ "БАЛКОН ОТКРЫТ":
      • Логично: холодно потому что проветриваете
      • Без открытого окна уведомление не отправляется (может быть поломка отопления)

      ЗАДЕРЖКА 1 МИНУТА:
      • Подтверждение устойчиво низкой температуры
      • Защита от ложных срабатываний

      ПРИМЕРЫ:
      1. T = 19°C, балкон открыт, мастер дома → Уведомление
      2. T = 18°C, балкон закрыт → Уведомление НЕ отправляется
      3. T = 19°C, балкон открыт, никого нет → Уведомление НЕ отправляется
      4. T = 19°C, балкон открыт, было уведомление 10 мин назад → Уведомление НЕ отправляется
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id: sensor.temperatura_v_spalne_sglazhennaia
        below: 20
        for:
          minutes: 1

    conditions:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"

      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"

      - condition: state
        entity_id: binary_sensor.0x00158d00044d5d11_contact
        state: "on"

      - condition: state
        entity_id: binary_sensor.someone_is_home_2
        state: "on"

      - condition: template
        value_template: >-
          {{ states('sensor.temperatura_v_spalne_sglazhennaia') not in ['unknown', 'unavailable', ''] }}

      - condition: state
        entity_id: input_boolean.bedroom_th_notice
        state: "off"

    actions:
      - variables:
          current_temp: "{{ states('sensor.temperatura_v_spalne_sglazhennaia') }}"
          message: >-
            ❄️ Низкая температура в спальне!

            Температура: {{ current_temp }}°C (< 20°C)
            Балкон/окно: ОТКРЫТО

            Рекомендация: закройте балкон/окно в спальне.

      - choose:
          - conditions:
              - condition: state
                entity_id: person.master
                state: "home"
            sequence:
              - action: notify.send_message
                target:
                  entity_id: notify.telegram_master
                data:
                  message: "{{ message }}"

              - action: script.yandex_tts_temp_status

      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.bedroom_th_notice

      - action: timer.start
        target:
          entity_id: timer.bedroom_th_notice_reset
        data:
          duration: "00:{{ states('input_number.bedroom_low_th_notification_reset_period') | int(20) }}:00"

  # ==========================================================================
  # ВСПОМОГАТЕЛЬНЫЕ АВТОМАТИЗАЦИИ
  # ==========================================================================

  # --------------------------------------------------------------------------
  # Сброс флага антиспама
  # --------------------------------------------------------------------------
  - id: "fdf3d865-6bdb-4c9b-9acd-fa7f7dc432d6"
    alias: "Спальня: сброс флага антиспама уведомлений о температуре"
    description: >
      Автоматически сбрасывает флаг антиспама после таймаута.

      ТРИГГЕР:
      • Событие: timer.finished (bedroom_th_notice_reset)

      ДЕЙСТВИЯ:
      • Сброс флага bedroom_th_notice = OFF
      • Запись в лог

      НАЗНАЧЕНИЕ:
      • Разрешает отправку новых уведомлений
      • Автоматическое управление антиспамом

      ЛОГИКА:
      • Уведомление отправлено → флаг = ON → таймер 20 мин → флаг = OFF
      • Теперь можно отправить новое уведомление (если температура всё ещё низкая)
    mode: single
    triggers:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bedroom_th_notice_reset

    actions:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.bedroom_th_notice
