# packages/room_livingroom.yaml #
#################################

# Этот пакет конфигураций Home Assistant предназначен для интеллектуального
# управления климатическими устройствами в гостиной, включая кондиционер,
# очиститель воздуха и увлажнитель. Он обеспечивает автоматическое управление
# этими устройствами в зависимости от состояния двери между кухней и гостиной,
# повышая комфорт и эффективность использования.

# Вводные переменные
# climate_pre_restart_state: Хранит предыдущее состояние кондиционера при
# перезагрузке системы.
# fan_pre_restart_state: Хранит предыдущее состояние очистителя воздуха при
# перезагрузке системы.
# humidifier_pre_restart_state: Хранит предыдущее состояние увлажнителя воздуха
# при # перезагрузке системы.
# door_open_climate_pre_state: Фиксирует, был ли кондиционер включен до момента
# открытия двери.
# door_open_fan_pre_state: Фиксирует, был ли очиститель воздуха включен до
# момента открытия двери.
# door_open_humidifier_pre_state: Фиксирует, был ли увлажнитель воздуха включен
# до момента открытия двери.

input_boolean:
  climate_pre_restart_state:
    name: "Climate Pre-Restart State"
    initial: off
  fan_pre_restart_state:
    name: "Fan Pre-Restart State"
    initial: off
  humidifier_pre_restart_state:
    name: "Humidifier Pre-Restart State"
    initial: off
  door_open_climate_pre_state:
    name: "Climate Pre-State When Door Opened"
    initial: off
  door_open_fan_pre_state:
    name: "Fan Pre-State When Door Opened"
    initial: off
  door_open_humidifier_pre_state:
    name: "Humidifier Pre-State When Door Opened"
    initial: off

# Автоматизации
automation:
  # Климатическая техника
  # Отключение устройств при открытой двери
  # Отключает кондиционер, очиститель воздуха и увлажнитель при длительном
  # открытии двери между кухней и гостиной, сохраняя их предыдущее состояние для
  # последующего восстановления.

  - id: "f4e42442-155e-4d0a-87c2-3f21fd72025d"
    alias: "Гостиная: Климат, отключить устройства при открытии двери"
    description: "Отключает кондиционер, очиститель воздуха и увлажнитель при длительном открытии двери."
    trigger:
      platform: state
      entity_id: binary_sensor.doors_in_kitchen_livingroom
      to: "on"
      for:
        minutes: 1
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.konditsioner
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.door_open_climate_pre_state
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.zhimi_mb3_a5d3_switch_status
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.door_open_fan_pre_state
      - choose:
          - conditions:
              - condition: state
                entity_id: humidifier.smartmi_humidifier_rainforest_hum_dehum_3
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.door_open_humidifier_pre_state
      - service: climate.turn_off
        entity_id: climate.konditsioner
      - service: switch.turn_off
        entity_id: switch.zhimi_mb3_a5d3_switch_status
      - service: humidifier.turn_off
        entity_id: humidifier.smartmi_humidifier_rainforest_hum_dehum_3

  # Восстановление состояния устройств
  # После закрытия двери автоматически восстанавливает предыдущее состояние
  # кондиционера, очистителя воздуха и увлажнителя, основываясь на сохраненных
  # данных о их состоянии до открытия двери.
  - id: "0347cae6-1b2f-436a-a54c-792feafa9620"
    alias: "Гостиная: Климат, восстановление состояния устройств"
    description: "Восстанавливает состояние устройств при закрытии двери."
    trigger:
      platform: state
      entity_id: binary_sensor.doors_in_kitchen_livingroom
      to: "off"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.door_open_climate_pre_state
                state: "on"
            sequence:
              - service: climate.turn_on
                entity_id: climate.konditsioner
          - conditions:
              - condition: state
                entity_id: input_boolean.door_open_fan_pre_state
                state: "on"
            sequence:
              - service: switch.turn_on
                entity_id: switch.zhimi_mb3_a5d3_switch_status
          - conditions:
              - condition: state
                entity_id: input_boolean.door_open_humidifier_pre_state
                state: "on"
            sequence:
              - service: humidifier.turn_on
                entity_id: humidifier.smartmi_humidifier_rainforest_hum_dehum_3
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.door_open_climate_pre_state
          - input_boolean.door_open_fan_pre_state
          - input_boolean.door_open_humidifier_pre_state
