# /packages/room_bedroom.yaml
#############################
# Пакет конфигураций для спальни (room_bedroom).
# В этом файле описана автоматизация по экономии энергии при зарядке
# смартфонов ночью.
#
#############################

##############################################################################
#                             АВТОМАТИЗАЦИИ
##############################################################################

automation:
  # ------------------------------------------------------------------------
  # ЭКОНОМИЯ ЭНЕРГИИ: ОТКЛЮЧЕНИЕ РОЗЕТКИ ПРИ ЗАРЯДКЕ GOOGLE PIXEL 8 PRO НОЧЬЮ
  # ------------------------------------------------------------------------
  # Эта автоматизация предотвращает «перезарядку» и потенциальный перегрев
  # аккумулятора ночью. Если уровень заряда батареи телефона достигает 99%
  # и при этом телефон фактически «заряжается», розетка отключается.
  #
  # Дополнительные детали:
  # - Автоматизация работает только в промежутке с 01:00 до 07:00.
  # - Вы можете изменить "above: 99" на нужное вам значение (например, 95),
  #   если хотите прерывать зарядку ещё раньше.
  # - Задержка (for: 1 минута) служит для гарантии того, что уровень заряда
  #   действительно стабильно находится на уровне 99+%.
  # ------------------------------------------------------------------------
  - id: "1711479406635"
    alias: "Спальня: Отключение розетки при зарядке телефона Андрея ночью"
    description: >
      Автоматизация по экономии энергии и продлению срока службы батареи Google Pixel 8 PRO.
      Если аккумулятор достигает уровня заряда в 99+% в период с 01:00 до 07:00,
      розетка автоматически отключается, чтобы избежать перезарядки и потенциального
      перегрева устройства.

    # Триггер: наблюдаем уровень заряда батареи.
    trigger:
      - platform: numeric_state
        entity_id: sensor.pixel_8_pro_battery_level
        above: 99 # Срабатывает при превышении 99%
        for:
          minutes: 1 # Удерживаем 99%+ в течение минуты

    # Условия:
    # 1) Датчик батареи должен показывать "charging" (то есть телефон реально на зарядке).
    # 2) Действие выполняется только в ночном промежутке 01:00–07:00.
    condition:
      - condition: state
        entity_id: sensor.pixel_8_pro_battery_state
        state: "charging"
      - condition: time
        after: "01:00:00"
        before: "07:00:00"

    # Действие: Выключаем розетку.
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.0x00158d0002530ba3

    mode: single

  - id: "3b13588c-5421-42a5-951b-a4d04d878041"
    alias: "Спальня: Отключение розетки при зарядке телефона Татьяны ночью"
    description: >
      Автоматизация по экономии энергии и продлению срока службы батареи Google Pixel 8 PRO.
      Если аккумулятор достигает уровня заряда в 99+% в период с 01:00 до 07:00,
      розетка автоматически отключается, чтобы избежать перезарядки и потенциального
      перегрева устройства.

    # Триггер: наблюдаем уровень заряда батареи.
    trigger:
      - platform: numeric_state
        entity_id: sensor.iphone_tatsiana_3_battery_level
        above: 99 # Срабатывает при превышении 99%
        for:
          minutes: 1 # Удерживаем 99%+ в течение минуты

    # Условия:
    # 1) Датчик батареи должен показывать "charging" (то есть телефон реально на зарядке).
    # 2) Действие выполняется только в ночном промежутке 01:00–07:00.
    condition:
      - condition: state
        entity_id: sensor.iphone_tatsiana_3_battery_state
        state: "charging"
      - condition: time
        after: "01:00:00"
        before: "07:00:00"

    # Действие: Выключаем розетку.
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.0x00158d0002530bd9

    mode: single
