# packages/room_livingroom.yaml #
#################################

# Этот пакет конфигураций Home Assistant предназначен для интеллектуального
# управления климатическими устройствами в гостиной, включая кондиционер,
# очиститель воздуха и увлажнитель. Он обеспечивает автоматическое управление
# этими устройствами в зависимости от состояния двери между кухней и гостиной,
# повышая комфорт и эффективность использования.

# Автоматизации
automation:
  # Управляет включением и выключением бра в гостиной при нажатии сценического
  # выключателя.
  # Это удобно для создания атмосферного или расслабляющего освещения в гостиной
  # без необходимости взаимодействия с традиционными выключателями.
  - id: "1712818445736"
    alias: "Гостиная: переключение бра сценическим выключателем"
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 719cda594198c3eafa3817b9230f2afa
        type: action
        subtype: 4_single
    condition: []
    action:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.livingroom_scone_dimmer
    mode: single

  # Позволяет управлять основным светом в гостиной с помощью сценического
  # выключателя. Автоматизация удобна для быстрого переключения света при входе
  # в комнату или изменении активности, требующей другого освещения.
  - id: "1712818610357"
    alias: "Гостиная: переключение люстры сценическим выключателем"
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 719cda594198c3eafa3817b9230f2afa
        type: action
        subtype: 3_single
    condition: []
    action:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.livingroom_main_switch_left
    mode: single

  # Климатическая техника
  # Отключение устройств при открытой двери
  # Отключает кондиционер, очиститель воздуха и увлажнитель при длительном
  # открытии двери между кухней и гостиной, сохраняя их предыдущее состояние для
  # последующего восстановления.
  - id: "f4e42442-155e-4d0a-87c2-3f21fd72025d"
    alias: "Гостиная: Климат, отключить устройства при открытии двери"
    description: "Отключает кондиционер, очиститель воздуха и увлажнитель при длительном открытии двери."
    trigger:
      platform: state
      entity_id: binary_sensor.doors_in_kitchen_livingroom
      to: "on"
      for:
        minutes: 1
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.konditsioner
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.door_open_climate_pre_state
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.zhimi_mb3_a5d3_switch_status
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.door_open_fan_pre_state
      - choose:
          - conditions:
              - condition: state
                entity_id: humidifier.smartmi_humidifier_rainforest_hum_dehum_3
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.door_open_humidifier_pre_state
      - service: climate.turn_off
        entity_id: climate.konditsioner
      - service: switch.turn_off
        entity_id: switch.zhimi_mb3_a5d3_switch_status
      - service: switch.turn_off
        entity_id: switch.livingroom_socket_l

  # Восстановление состояния устройств
  # После закрытия двери автоматически восстанавливает предыдущее состояние
  # кондиционера, очистителя воздуха и увлажнителя, основываясь на сохраненных
  # данных о их состоянии до открытия двери.
  - id: "0347cae6-1b2f-436a-a54c-792feafa9620"
    alias: "Гостиная: Климат, восстановление состояния устройств"
    description: "Восстанавливает состояние устройств при закрытии двери."
    trigger:
      platform: state
      entity_id: binary_sensor.doors_in_kitchen_livingroom
      to: "off"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.door_open_climate_pre_state
                state: "on"
            sequence:
              - service: climate.turn_on
                entity_id: climate.konditsioner
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.door_open_fan_pre_state
                state: "on"
            sequence:
              - service: switch.turn_on
                entity_id: switch.zhimi_mb3_a5d3_switch_status
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.door_open_humidifier_pre_state
                state: "on"
            sequence:
              - service: switch.turn_on
                entity_id: switch.livingroom_socket_l
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.door_open_climate_pre_state
          - input_boolean.door_open_fan_pre_state
          - input_boolean.door_open_humidifier_pre_state
