################################################################################
# /packages/room_workroom.yaml
################################################################################
#
# Назначение:
#   Данный пакет Home Assistant управляет подсветкой рабочей зоны (working_room_led)
#   в кабинете. Он обеспечивает удобное включение/выключение света одной кнопкой
#   (через Zigbee2MQTT или иной MQTT-протокол).
#
# Структура:
#   automation:
#     1) "Кабинет: Вкл/выкл подсветки рабочей зоны кнопкой" —
#        срабатывает на одиночное нажатие кнопки (single) и переключает (toggle)
#        состояние подсветки рабочего стола.
#
# Особенности:
#   • Используется domain: mqtt c type: action и subtype: single.
#     Это связано с тем, что Zigbee2MQTT 2.0+ отправляет в HA события вида
#     device_id: ... , discovery_id: ... , subtype: single и т.д.
#   • Automation не имеет дополнительных условий (condition: []),
#     поэтому реакция происходит при каждом одиночном нажатии.
#   • В action применяется команда "toggle" для light.working_room_led:
#     если свет выключен, он включится; если включен — выключится.
#
################################################################################

automation:
  # ----------------------------------------------------------------------------
  # 1) ВКЛ/ВЫКЛ ПОДСВЕТКИ РАБОЧЕЙ ЗОНЫ КНОПКОЙ
  # ----------------------------------------------------------------------------
  # Автоматизация, которая реагирует на одиночное нажатие сцены (или кнопки).
  # По нажатию subtype: single происходит переключение (toggle) состояния
  # подсветки рабочего стола в кабинете (light.working_room_led).
  #
  - id: "29873ab9-335c-4c39-9898-b01b5a482606"
    alias: "Кабинет: Вкл/выкл подсветки рабочей зоны кнопкой"
    description: >
      Когда пользователь нажимает физическую кнопку (subtype: single),
      переключаем (toggle) подсветку рабочего стола (working_room_led).
    trigger:
      - platform: device
        domain: mqtt
        device_id: 8067572bca7252311fc2ce6152f90f34
        type: action
        subtype: single
        discovery_id: "0x00158d0003cffd82 action_single"
    condition: []
    action:
      - type: toggle
        device_id: 3a9919ab25ad577158f751a70c35f8e2
        entity_id: light.working_room_led
        domain: light
    mode: single
