################################################################################
# /packages/room_hallway.yaml
################################################################################
#
# Этот пакет Home Assistant настроен для автоматизации освещения в прихожей,
# обеспечивая удобство и эффективность управления светом. Включает в себя
# автоматизации для реагирования на действия пользователя и изменения в
# окружающей среде, а также таймер для контроля продолжительности включения
# света.
#
################################################################################

##############################################################################
#                             ВХОДНЫЕ БУЛЕВЫ ПЕРЕМЕННЫЕ
##############################################################################
input_boolean:
  hallway_first_door_open:
    name: "Первое открытие двери в прихожей"
    initial: off
    icon: mdi:door-open

##############################################################################
#                                ТАЙМЕРЫ
##############################################################################
timer:
  timer_hallway:
    name: "Движение отсутствует"
    duration: "00:01:30"

##############################################################################
#                             АВТОМАТИЗАЦИИ
##############################################################################
automation:
  # Автоматизация включения/выключения света в прихожей по кнопке
  - id: "fc57ec27-9c9d-489a-8f5f-050b489466f7"
    alias: "Прихожая: Вкл/выкл света кнопкой"
    description: >
      Реагирует на нажатие кнопки, включая или выключая освещение в прихожей.
      После включения света также запускается таймер для автоматического
      выключения по истечении времени.
    triggers:
      - platform: device
        domain: mqtt
        device_id: cfd464e1cbfa3da2ddd4f2109d74eb4e
        type: action
        subtype: single
    actions:
      - type: toggle
        device_id: 61c0ac07893316543e261176eb0cb5f9
        entity_id: 89add52cab26b9b6bcad7e86fd6387ec
        domain: light
      - choose:
          - conditions:
              - condition: state
                entity_id: light.hallway_switch
                state: "on"
            sequence:
              - service: timer.start
                target:
                  entity_id: timer.timer_hallway
    mode: single

  # Автоматизация включения/выключения света в прихожей при открытии двери
  - id: "3c9a07a9-58ee-4287-87ee-734687c93bba"
    alias: "Прихожая: Включение освещения при открытии двери"
    description: >
      Реагирует на открытие двери, включая свет в прихожей. После включения света
      запускается таймер для автоматического выключения.
    triggers:
      - platform: state
        entity_id: binary_sensor.hallway_door_contact
        to: "on"
    conditions:
      - condition: state
        entity_id: light.hallway_switch
        state: "off"
      - condition: time
        after: "08:30:00"
        before: "23:00:00"
    actions:
      - service: light.turn_on
        target:
          entity_id: light.hallway_switch
      - service: timer.start
        target:
          entity_id: timer.timer_hallway
    mode: single

  # Вкл света при движении и низкой освещенности
  - id: "7f815fb8-98f4-437a-96fc-06984d9a4a25"
    alias: "Прихожая: Вкл света при движении и низкой освещенности"
    description: >
      Включает свет при обнаружении движения и низкой освещенности в прихожей.
      Свет включается на короткое время и автоматически выключается, если движения
      не обнаружено.
    triggers:
      - platform: state
        entity_id: binary_sensor.hallway_motion_occupancy
        to: "on"
    conditions:
      - condition: numeric_state
        entity_id: sensor.illumination_04cf8c977cdd
        below: 250
    actions:
      - service: light.turn_on
        target:
          entity_id: light.gateway_light_04cf8c977cdd
        data:
          brightness_pct: 7
      - service: timer.start
        target:
          entity_id: timer.timer_hallway
    mode: single

  # Запуск таймера при отсутствии движения
  - id: "3b6e37de-3b10-4201-afad-221dbe4cd4a0"
    alias: "Прихожая: Запуск таймера при отсутствии движения"
    description: >
      Запускает таймер, когда в прихожей отсутствует движение.
    triggers:
      - platform: state
        entity_id: binary_sensor.hallway_motion_occupancy
        to: "off"
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: light.hallway_switch
            state: "on"
          - condition: state
            entity_id: light.gateway_light_04cf8c977cdd
            state: "on"
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"
    actions:
      - service: timer.start
        target:
          entity_id: timer.timer_hallway

  # Сброс таймера при обнаружении движения
  - id: "479b917d-e4c2-4149-97e7-d12779b9f3ce"
    alias: "Прихожая: Перезапуск таймера при обнаружении движения"
    description: >
      Перезапускает таймер при обнаружении движения в прихожей.
    triggers:
      - platform: state
        entity_id: binary_sensor.hallway_motion_occupancy
        to: "on"
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: light.hallway_switch
            state: "on"
          - condition: state
            entity_id: light.gateway_light_04cf8c977cdd
            state: "on"
    actions:
      - service: timer.cancel
        target:
          entity_id: timer.timer_hallway
      - service: timer.start
        target:
          entity_id: timer.timer_hallway

  # Выключение света по таймеру
  - id: "7f6bdbae-a73b-4509-8db8-43f71a3525ca"
    alias: "Прихожая: Выключение света по таймеру"
    description: >
      Выключает освещение в прихожей по истечении времени таймера, экономя электроэнергию.
      Не работает в режиме уборки.
    triggers:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_hallway
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"
    actions:
      - service: light.turn_off
        target:
          entity_id:
            - light.hallway_switch
            - light.gateway_light_04cf8c977cdd
    mode: single

  # Новая автоматизация: включение света при первом открытии двери после прихода
  - id: "first-door-home-automation"
    alias: "Прихожая: Включение света при первом открытии двери после прихода домой"
    description: >
      Если пользователь (person.master) стал дома, то при первом открытии входной двери,
      если с момента прихода дверь еще не открывалась (флаг hallway_first_door_open = off)
      и время с прихода менее 10 минут, включается свет в прихожей.
    triggers:
      - platform: state
        entity_id: binary_sensor.hallway_door_contact
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.hallway_first_door_open
        state: "off"
      - condition: state
        entity_id: person.master
        state: "home"
      - condition: template
        value_template: >
          {{ (as_timestamp(now()) - as_timestamp(states.person.master.last_changed)) < 600 }}
    actions:
      - service: light.turn_on
        target:
          entity_id: light.hallway_switch
      - service: light.turn_on
        target:
          entity_id: light.gateway_light_04cf8c977cdd
        data:
          brightness_pct: 100
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.hallway_first_door_open
      - service: timer.start
        target:
          entity_id: timer.timer_hallway
    mode: single

  # Автоматизация сброса флага первого открытия двери при уходе пользователя
  - id: "reset-first-door-flag"
    alias: "Прихожая: Сброс флага первого открытия двери"
    description: >
      Сбрасывает флаг первого открытия входной двери, когда пользователь (person.master)
      переходит в состояние not_home.
    triggers:
      - platform: state
        entity_id: person.master
        to: "not_home"
    actions:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.hallway_first_door_open
    mode: single

  # Оповещения о нажатии кнопки звонка на входной двери
  - id: "37a7b942-71ea-456e-8f9e-1718c8c34a8d"
    alias: "Уведомление. Яндекс: Звонок в дверь"
    description: >
      Алиса произносит случайную фразу и мигает светом через Xiaomi Gateway при нажатии кнопки.
    triggers:
      - platform: device
        domain: mqtt
        device_id: d2c3001cdc59660c456de45aec09da91
        type: action
        subtype: single
    actions:
      - service: script.yandex_tts_click_outdoor_button # Вызов скрипта для воспроизведения звука
      - repeat:
          count: 3
          sequence:
            - service: light.turn_on
              target:
                entity_id:
                  - light.gateway_light_04cf8c977cdd
                  - light.working_room_led
            - delay: "00:00:01"
            - service: light.turn_off
              target:
                entity_id:
                  - light.gateway_light_04cf8c977cdd
                  - light.working_room_led
            - delay: "00:00:01"
      - choose:
          - conditions:
              - condition: state
                entity_id: light.working_room_led
                state: "off"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.working_room_led
    mode: single

  # Обнаружение попыток снятия входной кнопки и отправка предупреждения
  - id: "26345165-2c00-489c-af7b-c4b92110c937"
    alias: "Уведомление. Входную кнопку пытаются снять"
    description: >
      Обнаружение попыток снятия входной кнопки и отправка предупреждения.
    triggers:
      - platform: device
        domain: mqtt
        device_id: d2c3001cdc59660c456de45aec09da91
        type: action
        subtype: shake
    actions:
      - service: script.yandex_tts_shaking_outdoor_button
      - service: notify.master
        data:
          message: "⚠️ Внимание! Входную кнопку пытаются снять 🛑"
    mode: single
