################################################################################
# /packages/room_bathroom_lights.yaml
################################################################################
#
# УПРАВЛЕНИЕ ОСВЕЩЕНИЕМ ВАННОЙ КОМНАТЫ
#
# ФУНКЦИИ:
# 1. Автоматическое управление освещением
#    • Автоматическое включение по движению/открытию двери
#    • Выбор режима освещения (дневной/ночной) по времени суток
#    • Таймер автоматического выключения (настраиваемый)
#    • Режим уборки (бесконечное горение)
#    • Защита от ложных срабатываний при запуске HA
#
# 2. Резервное освещение
#    • Автоматическое включение основного света при недоступности спотов
#    • Уведомления о проблемах с освещением
#
# 3. Ручное управление
#    • MQTT-выключатель (левая кнопка)
#    • Переключение дневной/ночной режим
#
# УСТРОЙСТВА:
# • 5x Philips Downlight (точечные светильники)
# • 1x Relay L2 (основной потолочный свет)
# • MQTT Switch (настенный выключатель)
# • 2x датчика движения (см. room_bathroom.yaml)
# • 2x датчика открытия двери (см. room_bathroom.yaml)
#
# РЕЖИМЫ ОСВЕЩЕНИЯ:
# ┌──────────────────────────────────────────────────────────────────┐
# │ НОЧНОЙ (00:30-06:00):                                            │
# │ • 1 спот (L1) на 10% яркости                                     │
# │ • Мягкий свет для комфорта ночью                                 │
# ├──────────────────────────────────────────────────────────────────┤
# │ ДНЕВНОЙ (06:00-00:30):                                           │
# │ • 5 спотов на 100% яркости                                       │
# │ • Основной свет (relay L2)                                       │
# │ • Максимальная освещённость                                      │
# └──────────────────────────────────────────────────────────────────┘
#
# ЛОГИКА ТАЙМЕРА:
# ┌──────────────────────────────────────────────────────────────────┐
# │ 1. Движение обнаружено                                           │
# │    ↓                                                             │
# │ 2. Включение света (дневной/ночной режим)                        │
# │    ↓                                                             │
# │ 3. Движение прекратилось                                         │
# │    ↓                                                             │
# │ 4. Ожидание 1 минута (защита от ложных срабатываний)             │
# │    ↓                                                             │
# │ 5. Запуск таймера (настраиваемый, по умолчанию 3 минуты)         │
# │    ↓                                                             │
# │ 6. Таймер истёк → Выключение света                               │
# │                                                                  │
# │ ПРЕРЫВАНИЕ ТАЙМЕРА:                                              │
# │ • Новое движение → Отмена таймера                                │
# │ • Режим уборки → Таймер не запускается                           │
# └──────────────────────────────────────────────────────────────────┘
#
################################################################################

##############################################################################
#                          НАСТРАИВАЕМЫЕ ПАРАМЕТРЫ
##############################################################################

input_number:
  # ==========================================================================
  # Длительность таймера автоматического выключения
  # ==========================================================================
  bathroom_timer_duration:
    name: "Ванная: таймер автовыключения света (мин)"
    min: 0.5
    max: 10
    step: 0.5
    initial: 3
    unit_of_measurement: "мин"
    icon: mdi:timer-outline

##############################################################################
#                               ОСВЕЩЕНИЕ
##############################################################################

light:
  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_r1_philips
    host: !secret bathroom_spot_r1_ip
    token: !secret bathroom_spot_r1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_r2_philips
    host: !secret bathroom_spot_r2_ip
    token: !secret bathroom_spot_r2_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_l1_philips
    host: !secret bathroom_spot_l1_ip
    token: !secret bathroom_spot_l1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_c1_philips
    host: !secret bathroom_spot_c1_ip
    token: !secret bathroom_spot_c1_token
    model: philips.light.downlight

  - platform: xiaomi_miio_philipslight
    name: Bathroom_spot_c2_philips
    host: !secret bathroom_spot_c2_ip
    token: !secret bathroom_spot_c2_token
    model: philips.light.downlight

##############################################################################
#                                 ГРУППЫ
##############################################################################

group:
  bathroom_all_lights:
    name: "Ванная: все светильники"
    entities:
      - light.bathroom_spot_r1_philips
      - light.bathroom_spot_r2_philips
      - light.bathroom_spot_l1_philips
      - light.bathroom_spot_c1_philips
      - light.bathroom_spot_c2_philips
      - light.bathroom_relay_l2

  bathroom_spots:
    name: "Ванная: точечные светильники"
    entities:
      - light.bathroom_spot_r1_philips
      - light.bathroom_spot_r2_philips
      - light.bathroom_spot_l1_philips
      - light.bathroom_spot_c1_philips
      - light.bathroom_spot_c2_philips

  bathroom_night_lights:
    name: "Ванная: ночное освещение"
    entities:
      - light.bathroom_spot_l1_philips

##############################################################################
#                          БИНАРНЫЕ СЕНСОРЫ
##############################################################################

binary_sensor:
  - platform: template
    sensors:
      is_night_mode:
        unique_id: bathroom_is_night_mode
        friendly_name: "Ванная: ночной режим освещения"
        device_class: light
        value_template: >-
          {% set current_time = now().strftime('%H:%M') %}
          {{ '00:30' <= current_time < '06:00' }}
        icon_template: >-
          {% if is_state('binary_sensor.is_night_mode', 'on') %}
            mdi:weather-night
          {% else %}
            mdi:weather-sunny
          {% endif %}

##############################################################################
#                                ТАЙМЕРЫ
##############################################################################

timer:
  timer_bathroom:
    name: "Ванная: таймер автовыключения"
    duration: "00:03:00"
    icon: mdi:timer-off-outline

##############################################################################
#                                СКРИПТЫ
##############################################################################

script:
  bathroom_toggle_night_mode:
    alias: "Ванная: переключение ночного режима"
    icon: mdi:weather-night
    sequence:
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: light.bathroom_spot_l1_philips
                    state: "on"
                  - condition: state
                    entity_id: light.bathroom_relay_l2
                    state: "on"
            sequence:
              - action: light.turn_off
                target:
                  entity_id: group.bathroom_all_lights

        default:
          - action: light.turn_on
            target:
              entity_id: light.bathroom_spot_l1_philips
            data:
              brightness_pct: 10

          - action: timer.start
            target:
              entity_id: timer.timer_bathroom
            data:
              duration: "{{ (states('input_number.bathroom_timer_duration') | float(3) * 60) | int }}"

  bathroom_toggle_day_mode:
    alias: "Ванная: переключение дневного режима"
    icon: mdi:weather-sunny
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: group.bathroom_all_lights
                state: "on"
            sequence:
              - action: light.turn_off
                target:
                  entity_id: group.bathroom_all_lights

        default:
          - action: light.turn_on
            target:
              entity_id: light.bathroom_relay_l2

          - action: light.turn_on
            target:
              entity_id: group.bathroom_spots
            data:
              brightness_pct: 100

          - action: timer.start
            target:
              entity_id: timer.timer_bathroom
            data:
              duration: "{{ (states('input_number.bathroom_timer_duration') | float(3) * 60) | int }}"

  bathroom_turn_on_night_mode:
    alias: "Ванная: включение ночного освещения"
    icon: mdi:lightbulb-night-outline
    sequence:
      - action: light.turn_on
        target:
          entity_id: light.bathroom_spot_l1_philips
        data:
          brightness_pct: 10

  bathroom_turn_on_day_mode:
    alias: "Ванная: включение дневного освещения"
    icon: mdi:lightbulb-on-outline
    sequence:
      - action: light.turn_on
        target:
          entity_id: light.bathroom_relay_l2

      - action: light.turn_on
        target:
          entity_id: group.bathroom_spots
        data:
          brightness_pct: 100

##############################################################################
#                             АВТОМАТИЗАЦИИ
##############################################################################

automation:
  - id: "5525cbdc-3a8d-4464-908e-795c8205b40c"
    alias: "Ванная: переключение света с выключателя"
    mode: restart
    description: >
      Управление освещением через настенный MQTT-выключатель (левая кнопка).
    triggers:
      - trigger: device
        domain: mqtt
        device_id: cc6ef89720abb376a24e910e13f37902
        type: action
        subtype: single_left

    conditions:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"

    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.is_night_mode
                state: "on"
            sequence:
              - action: script.turn_on
                target:
                  entity_id: script.bathroom_toggle_night_mode
        default:
          - action: script.turn_on
            target:
              entity_id: script.bathroom_toggle_day_mode

  - id: "0007279c-13b5-402b-9aef-bf264273fa90"
    alias: "Ванная: автовключение света по движению"
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.bathroom_open_door
        from: "off"
        to: "on"
      - trigger: state
        entity_id: binary_sensor.bathroom_motions
        from: "off"
        to: "on"

    conditions:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.bathroom_lights_startup_protection
        state: "off"
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.someone_is_home_2
            state: "on"
          - condition: state
            entity_id: input_boolean.bathroom_cleaning_mode
            state: "on"

    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.is_night_mode
                state: "on"
            sequence:
              - action: script.turn_on
                target:
                  entity_id: script.bathroom_turn_on_night_mode
        default:
          - action: script.turn_on
            target:
              entity_id: script.bathroom_turn_on_day_mode

  - id: "50323f55-c6dd-483a-8799-af3c57e3e363"
    alias: "Ванная: отмена таймера (новое движение)"
    mode: single
    triggers:
      - trigger: state
        entity_id: binary_sensor.bathroom_motions
        to: "on"
    conditions:
      - condition: state
        entity_id: timer.timer_bathroom
        state: "active"
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"
    actions:
      - action: timer.cancel
        target:
          entity_id: timer.timer_bathroom
      - variables:
          tr_ent: >-
            {{ trigger.entity_id if trigger is defined and 'entity_id' in trigger else '' }}
          tr_from: >-
            {{ trigger.from_state.state if trigger is defined and 'from_state' in trigger and trigger.from_state is not none else '' }}
          tr_to: >-
            {{ trigger.to_state.state if trigger is defined and 'to_state' in trigger and trigger.to_state is not none else '' }}

  - id: "e519fa4c-bbad-4b0d-b06c-8521b3b10131"
    alias: "Ванная: запуск таймера (нет движения 1 мин)"
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.bathroom_motions
        to: "off"
        for:
          minutes: 1
    conditions:
      - condition: state
        entity_id: group.bathroom_all_lights
        state: "on"
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"
    actions:
      - action: timer.start
        target:
          entity_id: timer.timer_bathroom
        data:
          duration: "{{ (states('input_number.bathroom_timer_duration') | float(3) * 60) | int }}"
      - variables:
          tr_ent: >-
            {{ trigger.entity_id if trigger is defined and 'entity_id' in trigger else '' }}
          tr_from: >-
            {{ trigger.from_state.state if trigger is defined and 'from_state' in trigger and trigger.from_state is not none else '' }}
          tr_to: >-
            {{ trigger.to_state.state if trigger is defined and 'to_state' in trigger and trigger.to_state is not none else '' }}

  - id: "b30b7ad8-6563-4279-a78f-1a113f9cb252"
    alias: "Ванная: выключение света по таймеру"
    mode: single
    triggers:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_bathroom

    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_cleaning_mode
        state: "off"

    actions:
      - action: light.turn_off
        target:
          entity_id: group.bathroom_all_lights

      - action: script.log_helper_event
        data:
          level: info
          message: "Ванная: свет выключен по таймеру (отсутствие активности)."
          source: "{{ this.entity_id }}"
          trigger_entity: "timer.timer_bathroom"
          trigger_from: "active"
          trigger_to: "finished"
          extra: "action=timer_off;group=group.bathroom_all_lights"

  - id: "0c5020c3-e674-4789-8086-38dbc07253d7"
    alias: "Ванная: резервный свет (споты недоступны)"
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - light.bathroom_spot_r1_philips
          - light.bathroom_spot_r2_philips
          - light.bathroom_spot_l1_philips
          - light.bathroom_spot_c1_philips
          - light.bathroom_spot_c2_philips
        to: "unavailable"
        for:
          seconds: 30

    conditions:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.bathroom_lights_startup_protection
        state: "off"
      - condition: state
        entity_id: light.bathroom_relay_l2
        state: "off"
      - condition: template
        value_template: >-
          {% set unavailable_count =
            [ states.light.bathroom_spot_r1_philips,
              states.light.bathroom_spot_r2_philips,
              states.light.bathroom_spot_l1_philips,
              states.light.bathroom_spot_c1_philips,
              states.light.bathroom_spot_c2_philips ]
            | selectattr('state', 'eq', 'unavailable')
            | list | length %}
          {{ unavailable_count >= 2 }}

    actions:
      - action: light.turn_on
        target:
          entity_id: light.bathroom_relay_l2

      - action: notify.send_message
        target:
          entity_id: notify.telegram_master
        data:
          message: >-
            ⚠️ Ванная: резервный свет включён автоматически.
            Причина: {{
              [ states.light.bathroom_spot_r1_philips,
                states.light.bathroom_spot_r2_philips,
                states.light.bathroom_spot_l1_philips,
                states.light.bathroom_spot_c1_philips,
                states.light.bathroom_spot_c2_philips ]
              | selectattr('state', 'eq', 'unavailable')
              | list | length
            }} точечных спотов недоступны.

      - variables:
          tr_ent: >-
            {{ trigger.entity_id if trigger is defined and 'entity_id' in trigger else '' }}
          tr_from: >-
            {{ trigger.from_state.state if trigger is defined and 'from_state' in trigger and trigger.from_state is not none else '' }}
          tr_to: >-
            {{ trigger.to_state.state if trigger is defined and 'to_state' in trigger and trigger.to_state is not none else '' }}
          unavailable_list: >-
            {{
              [ states.light.bathroom_spot_r1_philips,
                states.light.bathroom_spot_r2_philips,
                states.light.bathroom_spot_l1_philips,
                states.light.bathroom_spot_c1_philips,
                states.light.bathroom_spot_c2_philips ]
              | selectattr('state', 'eq', 'unavailable')
              | map(attribute='entity_id')
              | list
            }}
          unavailable_count: "{{ unavailable_list | length }}"

  - id: "14a6f0ef-8217-4fc6-8dca-067875b950a7"
    alias: "Ванная: сброс света после рестарта HA"
    mode: single
    triggers:
      - trigger: homeassistant
        event: start

    actions:
      - delay: "00:01:30"

      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.bathroom_motions
            state: "off"
          - condition: state
            entity_id: input_boolean.bathroom_cleaning_mode
            state: "off"

      - action: light.turn_off
        target:
          entity_id:
            - group.bathroom_all_lights
            - light.bathroom_relay_l2

  - id: "048bc34f-9e6d-475c-84ed-0af54dedeed9"
    alias: "Ванная: защита от ложных срабатываний (5 мин после старта)"
    mode: single
    triggers:
      - trigger: homeassistant
        event: start
    actions:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.bathroom_lights_startup_protection
      - delay: "00:05:00"
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.bathroom_lights_startup_protection
