################################################################################
# /packages/scene_n_automation.yaml
################################################################################
#
# Пакет конфигураций для определения сцен и их переключения в зависимости от
# соблюдения требуемых условий.
# В том числе и вводные булевы для организации ручного переключения
#
################################################################################

################################################################################
#                            input_boolean
################################################################################
input_boolean:
  work_mode:
    name: "Режим «На работе»"
    initial: off


################################################################################
# СЦЕНЫ
################################################################################
scene:
# Режим "На работе"
# Отключает всё освещение, розетки в спальне, отпаривателя и угловой, медиа
#
  - id: scene_at_work
    name: "На работе"
    entities:
      light.all_lights: off
      switch.smart_plug_in_unit_vykliuchatel: off
      switch.0x00158d0002530bd9: off
      switch.0x00158d0002530ba3: off
      switch.livingroom_socket_corner_r: off
      group.living_room_tv: off
      media_player.yandex_station_ff98f0294437799304d0788d: off
      automation.vannaia_svet_vkl_po_dvizheniiu_datchikam_otkrytiia_i_pere_zapusk_taimera: off