################################################################################
# /packages/washing_machine.yaml
################################################################################
#
# Пакет конфигураций Home Assistant для контроля работы стиральной машины
# и уведомлений.
#
# Изменения/уточнения:
#  - Убраны упоминания про input_boolean.washing_machine_finished (остаётся только
#    binary_sensor.washing_machine_finished).
#  - Уведомление о завершении теперь отправляется в Telegram + TTS на Яндекс-колонку.
#  - Сброшен сервис notify.notify.
#
# Доработки на основе отзыва:
#  - Добавлен гистерезис в binary_sensor (delay_off для active, синхронизация delay_on).
#  - Объединены автоматизации для старта/окончания и сбросов при рестарте.
#  - Упрощены условия в уведомлениях (добавлен silent_mode в Telegram, проверки на someone_is_home).
#  - Добавлено логирование для ключевых событий.
#  - Минимальное время стирки уменьшено до 10 мин в шаблоне (настраиваемо).
#
################################################################################

input_number:
  wm_min_cycle_min:
    name: "Стиралка: минимальная длительность цикла (мин)"
    min: 5
    max: 180
    step: 5
    initial: 10

input_datetime:
  washing_machine_started_at:
    name: "Стиралка: время старта цикла"
    has_date: true
    has_time: true

input_boolean:
  washing_machine_running:
    name: "Стиральная машина работает"
    initial: off
    icon: mdi:washing-machine

  washing_machine_pre_restart_state:
    name: "Washing Machine Pre-Restart State"
    initial: off
    icon: mdi:washing-machine

binary_sensor:
  - platform: template
    sensors:
      washing_machine_active:
        friendly_name: "Стиральная машина активна"
        availability_template: >
          {{ states('sensor.bathroom_washing_machine_power') not in ['unknown', 'unavailable', ''] }}
        value_template: >
          {{ (states('sensor.bathroom_washing_machine_power') | float(0)) > 5 }}
        delay_off:
          minutes: 1  # игнорируем кратковременные спады мощности

      washing_machine_finished:
        friendly_name: "Стиральная машина завершила стирку"
        availability_template: >
          {{ states('sensor.bathroom_washing_machine_power') not in ['unknown', 'unavailable', ''] }}
        value_template: >
          {{ (states('sensor.bathroom_washing_machine_power') | float(0)) < 5 }}
        delay_on:
          minutes: 2  # устойчиво <5 Вт в течение 2 минут

automation:
  ##############################################################################
  # СОХРАНЕНИЕ/ВОССТАНОВЛЕНИЕ СОСТОЯНИЯ ПРИ SHUTDOWN/START HA
  ##############################################################################
  - id: "064cbd85-8d52-40ac-98bd-98164ad1434c"
    alias: "HELPER: Сохранение/восстановление состояния стиральной машины при рестарте HA"
    mode: single
    trigger:
      - platform: homeassistant
        event: shutdown
        id: shutdown
      - platform: homeassistant
        event: start
        id: start
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: shutdown
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: binary_sensor.washing_machine_active
                        state: "on"
                    sequence:
                      - service: input_boolean.turn_on
                        target:
                          entity_id: input_boolean.washing_machine_pre_restart_state
                default:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.washing_machine_pre_restart_state
          - conditions:
              - condition: trigger
                id: start
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: input_boolean.washing_machine_pre_restart_state
                        state: "on"
                    sequence:
                      - service: system_log.write
                        data:
                          message: "System start: стиральная машина была активна до перезагрузки."
                          level: warning
              - service: input_boolean.turn_off
                target:
                  entity_id:
                    - input_boolean.washing_machine_running
                    - input_boolean.washing_machine_pre_restart_state

  ##############################################################################
  # СТАТУС СТИРКИ: СТАРТ/ОКОНЧАНИЕ
  ##############################################################################
  - id: "04a14878-99d3-4030-a17d-bfa3c75b1f9b"
    alias: "HELPER: Стиральная машина: Управление статусом (старт/окончание)"
    description: "Включает running при >5 Вт; выключает при <5 Вт (2 мин), если цикл длился не меньше минимума."
    mode: restart
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_washing_machine_power
        above: 5
        id: start
      - platform: numeric_state
        entity_id: sensor.bathroom_washing_machine_power
        below: 5
        for:
          minutes: 2  # синхронизировано с delay_on finished-сенсора
        id: finish
    condition:
      - condition: template
        value_template: >
          {{ states('sensor.bathroom_washing_machine_power') not in ['unknown', 'unavailable'] }}
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: start
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.washing_machine_running
              - service: input_datetime.set_datetime
                target:
                  entity_id: input_datetime.washing_machine_started_at
                data:
                  datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
              - service: system_log.write
                data:
                  message: "Стиральная машина запущена."
                  level: info

          - conditions:
              - condition: trigger
                id: finish
              - condition: state
                entity_id: input_boolean.washing_machine_running
                state: "on"
              - condition: template
                value_template: >
                  {% set started = as_timestamp(states('input_datetime.washing_machine_started_at')) %}
                  {% set min_sec = (states('input_number.wm_min_cycle_min') | float(10) * 60) | int %}
                  {{ started is number and (now().timestamp() - started) >= min_sec }}
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.washing_machine_running
              - service: system_log.write
                data:
                  message: "Стиральная машина завершена."
                  level: info
        default:
          # Игнорируем ранний провал мощности (< минимальной длительности)
          - choose:
              - conditions:
                  - condition: trigger
                    id: finish
                  - condition: state
                    entity_id: input_boolean.washing_machine_running
                    state: "on"
                sequence:
                  - service: system_log.write
                    data:
                      message: "Низкая мощность обнаружена, но цикл < минимального времени — игнорируем окончание."
                      level: info

  ##############################################################################
  # УВЕДОМЛЕНИЕ О ЗАВЕРШЕНИИ СТИРКИ (TTS + TELEGRAM)
  ##############################################################################
  - id: "d1e78a7d-56c3-4d4e-b2a4-8a23f1a62a45"
    alias: "Уведомление: Стирка завершена (TTS + Telegram)"
    description: "При finished=on отправляет TTS и Telegram, если не startup/silent и цикл длился достаточно."
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_finished
        to: "on"
        for:
          minutes: 2  # доп. задержка для стабильности
    condition:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"
      - condition: state
        entity_id: binary_sensor.someone_is_home
        state: "on"
      - condition: state
        entity_id: input_boolean.washing_machine_running
        state: "off"
      - condition: template
        value_template: >
          {% set started = as_timestamp(states('input_datetime.washing_machine_started_at')) %}
          {% set min_sec = (states('input_number.wm_min_cycle_min') | float(10) * 60) | int %}
          {{ started is number and (now().timestamp() - started) >= min_sec }}
    action:
      - service: script.yandex_tts_washing_machine_finished
      - service: notify.master
        data:
          message: "🏠 Стирка закончена! 🧼"
      - service: system_log.write
        data:
          message: "Уведомление о завершении стирки отправлено."
          level: info

  ##############################################################################
  # НАПОМИНАНИЕ О ЗАВЕРШЕНИИ (ЕСЛИ НЕТ ДВИЖЕНИЯ)
  ##############################################################################
  - id: "washing_machine_reminder_no_motion"
    alias: "Уведомление: Напоминание о стирке при отсутствии движения"
    description: "Через 15 мин после finished=on, если нет движения и дверь закрыта — напомнить через TTS."
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_finished
        to: "on"
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"
      - condition: state
        entity_id: binary_sensor.someone_is_home
        state: "on"
      - condition: state
        entity_id: binary_sensor.bathroom_motions
        state: "off"
      - condition: state
        entity_id: binary_sensor.bathroom_open_door
        state: "off"
    action:
      - service: script.yandex_tts_washing_machine_reminder
      - service: system_log.write
        data:
          message: "Напоминание о стирке отправлено."
          level: info