################################################################################
# /packages/washing_machine.yaml
################################################################################
#
# Пакет конфигураций Home Assistant для контроля работы стиральной машины
# и уведомлений.
#
# Изменения/уточнения:
#  - Убраны упоминания про input_boolean.washing_machine_finished (остаётся только
#    binary_sensor.washing_machine_finished).
#  - Уведомление о завершении теперь отправляется в Telegram + TTS на Яндекс-колонку.
#  - Сброшен сервис notify.notify.
#
################################################################################

input_boolean:
  washing_machine_running:
    name: "Стиральная машина работает"
    initial: off
    icon: mdi:washing-machine
  # --------------------------------------------------------------------------
  # Washing Machine Pre-State When Door Opened
  # --------------------------------------------------------------------------
  # Это позволит «запомнить», что машина была включена и шёл цикл стирки
  # до перезагрузки (или, например, что стирка уже была завершена).
  # --------------------------------------------------------------------------
  washing_machine_pre_restart_state:
    name: "Washing Machine Pre-Restart State"
    initial: off
    icon: mdi:washing-machine
binary_sensor:
  - platform: template
    sensors:
      washing_machine_active:
        friendly_name: "Стиральная машина активна"
        value_template: >-
          {{ states('sensor.bathroom_washing_machine_power') | float(default=0) > 5 }}
        # Активна, если потребляет более 5 Вт

      washing_machine_finished:
        friendly_name: "Стиральная машина завершила стирку"
        value_template: >-
          {{ states('sensor.bathroom_washing_machine_power') | float(default=0) < 5 }}
        delay_on:
          minutes: 2
        # Активна, если потребляет менее 5 Вт в течение 2 минут подряд

automation:
  ##############################################################################
  #
  #
  # 1) Сохранение состояния стиральной машины при завершении работы HA
  #    - Если binary_sensor.washing_machine_active == on, то включаем washing_machine_pre_restart_state.
  #      Иначе выключаем.
  #
  # 2) Восстановление состояния стиральной машины при старте HA
  #    - Если washing_machine_pre_restart_state == on, значит
  #      стиральная машина «работала» до перезагрузки. Можно при желании
  #      включать какую-то логику (но поскольку сам binary_sensor.washing_machine_active —
  #      обычно «физический» датчик или приходящий с MQTT/ESPHome, мы не можем
  #      прямо выставить ему состояние).
  #    - Для предотвращения лишних уведомлений о «Завершении стирки», мы
  #      вторым действием (после проверки) выключаем флаг input_boolean.washing_machine_pre_restart_state,
  #      чтобы вернуть систему в согласованное состояние.
  #
  ##############################################################################
  # --------------------------------------------------------------------------
  # СОХРАНЕНИЕ СОСТОЯНИЯ СТИРАЛЬНОЙ МАШИНЫ ПРИ ЗАВЕРШЕНИИ РАБОТЫ HA
  # --------------------------------------------------------------------------
  # Если стиральная машина была «активна» при выключении, значит цикл
  # стирки не закончился до конца. Запомним это.
  - id: "064cbd85-8d52-40ac-98bd-98164ad1434c"
    alias: "HELPER: Сохранение состояния стиральной машины при завершении HA"
    mode: single
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.washing_machine_active
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.washing_machine_pre_restart_state
        default:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.washing_machine_pre_restart_state

  # --------------------------------------------------------------------------
  # ВОССТАНОВЛЕНИЕ СОСТОЯНИЯ СТИРАЛЬНОЙ МАШИНЫ ПРИ СТАРТЕ HA
  # --------------------------------------------------------------------------
  # Если при прошлом выключении HA стиралка работала, текущий
  # sensor.washing_machine_active может на короткий момент прийти в «off»
  # (зависит от опроса). Избегаем ложного «завершения».
  # Здесь вы можете при необходимости выполнить дополнительные действия,
  # если хотите явно восстановить «машина в процессе стирки». Но обычно
  # стиральная машина сама «сообщит» новый стейт (on/off), когда возникнет связь.
  #
  # В конце выключаем input_boolean.washing_machine_pre_restart_state, чтобы
  # всё вернулось в нормальное состояние.
  - id: "a49b7efb-5294-4361-90f2-73943aa71194"
    alias: "HELPER: Восстановление стиральной машины при старте HA"
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      # Здесь можно делать какую-то логику, если нужно.
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.washing_machine_pre_restart_state
                state: "on"
            sequence:
              - service: system_log.write
                data:
                  message: "System start: стиральная машина была активна до перезагрузки."
                  level: warning
        default: []
      # В любом случае гасим наш флаг.
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.washing_machine_pre_restart_state

  ##############################################################################
  # Сброс бегущего статуса (washing_machine_running) при старте системы
  ##############################################################################
  - id: "055f9541-0e9f-40c3-b786-1cc9d17b15bb"
    alias: "HELPER: Сброс статуса стиральной машины при старте системы"
    description: >
      При перезапуске HA сбрасываем флаг washing_machine_running в Off.
      (binary_sensor.washing_machine_finished автоматически «сам определится».)
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.washing_machine_running

  ##############################################################################
  # Сброс статуса при запуске стирки
  ##############################################################################
  # Если мощность стиралки поднялась выше 5 Вт => считаем, что начинается стирка.
  # Включаем washing_machine_running = on, сбрасываем «завершённость».
  #
  - id: "04a14878-99d3-4030-a17d-bfa3c75b1f9b"
    alias: "HELPER: Стиральная машина: Сброс статуса при запуске"
    description: >
      Когда машина начинает работать (мощность > 5), ставим
      input_boolean.washing_machine_running=on.
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_washing_machine_power
        above: 5
    action:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.washing_machine_running

  ##############################################################################
  # Завершение работы стиральной машины
  ##############################################################################
  # Если мощность упала ниже 5 Вт на 5 минут -> считаем, что цикл закончен.
  # Отключаем washing_machine_running (off).
  # (binary_sensor.washing_machine_finished перейдёт в on сам по себе.)
  #
  - id: "2d3371e6-23df-4710-be67-c79088517d33"
    alias: "HELPER: Стиральная машина: Завершение работы"
    description: >
      Если мощность < 5 на 5 минут подряд, считаем что стирка окончена.
      Отключаем washing_machine_running.
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_washing_machine_power
        below: 5
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.washing_machine_running
        state: "on"
    action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.washing_machine_running

  ##############################################################################
  # Уведомление о завершении стирки (через Телеграм и Яндекс)
  ##############################################################################
  # При переходе binary_sensor.washing_machine_finished в on:
  #   - проверяем, что система не в старте (system_startup_phase=off)
  #   - тихий режим выключен (silent_mode=off)
  #   - стиральная машина (washing_machine_running=off) - чтобы не уведомлять,
  #     если вдруг что-то пошло не так.
  # Отправляем уведомление в Телеграм + TTS-нагадалку в Яндекс-колонку.
  #
  - id: "d1e78a7d-56c3-4d4e-b2a4-8a23f1a62a45"
    alias: "Уведомление. Яндекс: Стирка: Завершена"
    description: >
      При завершении стирки (binary_sensor.washing_machine_finished=on), 
      отправляем уведомление в Телеграм и говорим на Яндекс-колонке.
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_finished
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.washing_machine_running
        state: "off"
    action:
      # Озвучка через Яндекс-колонку (скрипт вы уже используете)
      - service: script.yandex_tts_washing_machine_finished
    mode: single

  ##############################################################################
  # Напоминание, если нет движения 15 минут после завершения
  ##############################################################################
  # Если через 15 минут после завершения (washing_machine_finished=on) в ванной
  # не было движения и дверь не открывалась, воспроизводим ещё одно
  # голосовое напоминание.
  #
  - id: "washing_machine_reminder_no_motion"
    alias: "Уведомление. Яндекс: Стирка: Напоминание при отсутствии движения"
    description: >
      Через 15 минут после binary_sensor.washing_machine_finished=on,
      если нет движения в ванной (binary_sensor.bathroom_motions=off)
      и дверь не открыта (bathroom_open_door=off),
      озвучиваем дружеское напоминание через скрипт.
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_finished
        to: "on"
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"
      - condition: state
        entity_id: binary_sensor.bathroom_motions
        state: "off"
      - condition: state
        entity_id: binary_sensor.bathroom_open_door
        state: "off"
    action:
      - service: script.yandex_tts_washing_machine_reminder
    mode: single

  # ----------------------------------------------------------------------------
  # Уведомление: Завершение стирки
  # ----------------------------------------------------------------------------
  # Триггер — бинарный датчик (binary_sensor.washing_machine_finished).
  # Состояние "on" в течение 5 минут и при этом sensor.washing_machine_active
  # == off, плюс проверка по времени штамповому, чтобы избежать ложных
  # срабатываний. Если условия выполняются, отправляется уведомление
  # пользователю (master), что стирка окончена.
  # ----------------------------------------------------------------------------
  # --------------------------------------------------------------------------
  # УВЕДОМЛЕНИЕ О ЗАВЕРШЕНИИ СТИРКИ (не срабатывает во время старта)
  # --------------------------------------------------------------------------
  #      Уведомление о завершении стирки (модифицировано)
  #    - Добавили condition: system_startup_phase == off (чтобы при старте не срабатывало).
  #    - Ещё одна condition: washing_machine_pre_restart_state == off, чтобы если
  #      машина «якобы» была завершена прямо при перезагрузке — не выдать уведомление
  #      повторно на старте.
  # ----------------------------------------------------------------------------
  - id: "ba69e825-6c4e-4451-bb6f-cbbb224b1631"
    alias: "Уведомление. Телеграм: Завершении стирки"
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_finished
        to: "on"
        for:
          minutes: 5 # ждем 5 минут после того, как BINARY_SENSOR перешел в on
    condition:
      # a) Не срабатывать в фазе загрузки
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"

      # b) Дополнительно проверяем, что машина не была «уже завершена» до перезагрузки
      - condition: state
        entity_id: input_boolean.washing_machine_pre_restart_state
        state: "off"

      # c) Проверка: сама машина уже не активна
      #    Здесь меняем sensor.washing_machine_active → binary_sensor.washing_machine_active
      - condition: state
        entity_id: binary_sensor.washing_machine_active
        state: "off"

      # d) Проверка, что стиралка была «on» не менее 14 минут назад
      #    Аналогично, меняем states.sensor.washing_machine_active → states.binary_sensor.washing_machine_active
      - condition: template
        value_template: >
          {{ is_state('binary_sensor.washing_machine_active','on') and
            (as_timestamp(now()) -
              as_timestamp(states.binary_sensor.washing_machine_active.last_changed)) >= 840 }}
    action:
      - action: notify.master
        data:
          message: "🏠 Стирка закончена! 🧼"
