################################################################################
# /packages/washing_machine.yaml
################################################################################
#
# Пакет конфигураций Home Assistant для контроля работы стиральной машины
# и уведомлений.
#
# Изменения/уточнения:
#  - Убраны упоминания про input_boolean.washing_machine_finished (остаётся только
#    binary_sensor.washing_machine_finished).
#  - Уведомление о завершении теперь отправляется в Telegram + TTS на Яндекс-колонку.
#  - Сброшен сервис notify.notify.
#
################################################################################

input_boolean:
  washing_machine_running:
    name: "Стиральная машина работает"
    initial: off
    icon: mdi:washing-machine

binary_sensor:
  - platform: template
    sensors:
      washing_machine_active:
        friendly_name: "Стиральная машина активна"
        value_template: >-
          {{ states('sensor.bathroom_washing_machine_power') | float(default=0) > 5 }}
        # Активна, если потребляет более 5 Вт

      washing_machine_finished:
        friendly_name: "Стиральная машина завершила стирку"
        value_template: >-
          {{ states('sensor.bathroom_washing_machine_power') | float(default=0) < 5 }}
        delay_on:
          minutes: 2
        # Активна, если потребляет менее 5 Вт в течение 2 минут подряд

automation:
  ##############################################################################
  # 1) Сброс бегущего статуса (washing_machine_running) при старте системы
  ##############################################################################
  - id: "055f9541-0e9f-40c3-b786-1cc9d17b15bb"
    alias: "Сброс статуса стиральной машины при старте системы"
    description: >
      При перезапуске HA сбрасываем флаг washing_machine_running в Off.
      (binary_sensor.washing_machine_finished автоматически «сам определится».)
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.washing_machine_running

  ##############################################################################
  # 2) Сброс статуса при запуске стирки
  ##############################################################################
  # Если мощность стиралки поднялась выше 5 Вт => считаем, что начинается стирка.
  # Включаем washing_machine_running = on, сбрасываем «завершённость».
  #
  - id: "04a14878-99d3-4030-a17d-bfa3c75b1f9b"
    alias: "Стиральная машина: Сброс статуса при запуске"
    description: >
      Когда машина начинает работать (мощность > 5), ставим
      input_boolean.washing_machine_running=on.
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_washing_machine_power
        above: 5
    action:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.washing_machine_running

  ##############################################################################
  # 3) Завершение работы стиральной машины
  ##############################################################################
  # Если мощность упала ниже 5 Вт на 5 минут -> считаем, что цикл закончен.
  # Отключаем washing_machine_running (off).
  # (binary_sensor.washing_machine_finished перейдёт в on сам по себе.)
  #
  - id: "2d3371e6-23df-4710-be67-c79088517d33"
    alias: "Стиральная машина: Завершение работы"
    description: >
      Если мощность < 5 на 5 минут подряд, считаем что стирка окончена.
      Отключаем washing_machine_running.
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_washing_machine_power
        below: 5
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.washing_machine_running
        state: "on"
    action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.washing_machine_running

  ##############################################################################
  # 4) Уведомление о завершении стирки (через Телеграм и Яндекс)
  ##############################################################################
  # При переходе binary_sensor.washing_machine_finished в on:
  #   - проверяем, что система не в старте (system_startup_phase=off)
  #   - тихий режим выключен (silent_mode=off)
  #   - стиральная машина (washing_machine_running=off) - чтобы не уведомлять,
  #     если вдруг что-то пошло не так.
  # Отправляем уведомление в Телеграм + TTS-нагадалку в Яндекс-колонку.
  #
  - id: "d1e78a7d-56c3-4d4e-b2a4-8a23f1a62a45"
    alias: "Уведомление о завершении стирки"
    description: >
      При завершении стирки (binary_sensor.washing_machine_finished=on), 
      отправляем уведомление в Телеграм и говорим на Яндекс-колонке.
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_finished
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.washing_machine_running
        state: "off"
    action:
      # Озвучка через Яндекс-колонку (скрипт вы уже используете)
      - service: script.yandex_tts_washing_machine_finished
    mode: single

  ##############################################################################
  # 5) Напоминание, если нет движения 15 минут после завершения
  ##############################################################################
  # Если через 15 минут после завершения (washing_machine_finished=on) в ванной
  # не было движения и дверь не открывалась, воспроизводим ещё одно
  # голосовое напоминание.
  #
  - id: "washing_machine_reminder_no_motion"
    alias: "Напоминание о стирке при отсутствии движения"
    description: >
      Через 15 минут после binary_sensor.washing_machine_finished=on,
      если нет движения в ванной (binary_sensor.bathroom_motions=off)
      и дверь не открыта (bathroom_open_door=off),
      озвучиваем дружеское напоминание через скрипт.
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_finished
        to: "on"
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: binary_sensor.bathroom_motions
        state: "off"
      - condition: state
        entity_id: binary_sensor.bathroom_open_door
        state: "off"
    action:
      - service: script.yandex_tts_washing_machine_reminder
