# /packages/yandex_notifications #
#######################################

# Данный набор конфигураций представляет собой часть интеграции умного дома с
# Яндекс устройствами через Home Assistant, позволяя расширить возможности
# управления и взаимодействия с домашней автоматизацией. Конфигурация включает
# автоматизации для интерактивного взаимодействия с помощью Яндекс станции,

# Автоматизации для взаимодействия с Яндекс колонкой

automation:
  # Приветствие
  - id: "2f26dfda-2840-424a-a840-8c4acda8eaf6"
    alias: "Уведомление. Яндекс: Приветствие"
    description: "Отключение камеры, включение света в прихожей и доклад о климате"
    triggers:
      - platform: event
        event_type: yandex_speaker
        event_data:
          value: "С возвращением, дорогой мне человек! Я скучала без тебя!"
    conditions:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"
    actions:
      - service: light.turn_on
        target:
          entity_id: light.light_bathroom
      - delay:
          seconds: 4
      - service: script.yandex_tts_ppm_status
      - delay:
          seconds: 6
      - service: script.yandex_tts_temp_status
      - delay:
          seconds: 3
      - service: script.yandex_tts_hum_status
    mode: single

  # Прощание
  - id: "661464a3-ab6d-438e-847b-f2b6ddfee59a"
    alias: "Уведомление. Яндекс: Прощание"
    description: "Выключает весь свет в доме, включает камеру в полноцветном режиме и произносит прощальное сообщение через Яндекс колонку."
    triggers:
      - platform: event
        event_type: yandex_speaker
        event_data:
          value: "Я буду скучать! Возвращайся быстрее"
    actions:
      - delay: "00:00:04"
      - service: script.yandex_tts_door_status
      - service: light.turn_off
        target:
          entity_id: light.all_lights
      - service: switch.turn_on
        target:
          entity_id: group.cameras
      - choose:
          - conditions:
              - condition: state
                entity_id: person.master
                state: "home"
            sequence:
              - action: notify.master
                data:
                  message: "Свет в квартире выключен! Приятной дороги!"
          # - conditions:
          #     - condition: state
          #       entity_id: person.tatiana
          #       state: "home"
          #   sequence:
          #     - action: notify.tatiana
          #       data:
          #         message: "Свет в квартире выключен! Приятной дороги!"
    mode: single

  # Уведомление. Яндекс: Температура ниже установленного уровня
  - id: "a8c5eb07-9381-46d5-bc65-0f52dd7079a8"
    alias: "Уведомление. Яндекс: Температура ниже установленного уровня"
    description: ""
    triggers:
      - platform: state
        entity_id: binary_sensor.temperature_below_20
        to: "on"
        for:
          minutes: 1 # Убедимся, что состояние "on" устойчиво в течение 1 минуты
    conditions:
      - condition: state
        entity_id: input_boolean.system_startup_phase
        state: "off"
      - condition: state
        entity_id: input_boolean.silent_mode
        state: "off"
    actions:
      - service: script.yandex_tts_door_status
    mode: single
